# Shell Aliases Configuration

[general]
default_shells = ["zsh", "bash", "fish"]

[dependencies]
eza = { package = "pkgs.eza", binary = "eza" }
bat = { package = "pkgs.bat", binary = "bat" }
neovim = { package = "pkgs.neovim", binary = "nvim" }
fd = { package = "pkgs.fd", binary = "fd" }
ripgrep = { package = "pkgs.ripgrep", binary = "rg" }
htop = { package = "pkgs.htop", binary = "htop" }
duf = { package = "pkgs.duf", binary = "duf" }
ncdu = { package = "pkgs.ncdu", binary = "ncdu" }
prettyping = { package = "pkgs.prettyping", binary = "prettyping" }
viddy = { package = "pkgs.viddy", binary = "viddy" }
kubectl = { package = "pkgs.kubectl", binary = "kubectl" }
podmanCompose = { package = "pkgs.podman-compose", binary = "podman-compose" }
busybox = { package = "pkgs.busybox", binary = "busybox" }
fzf = { package = "pkgs.fzf", binary = "fzf" }
jq = { package = "pkgs.jq", binary = "jq" }

[[aliases]]
key = "ls"
dependency = "eza"
command = "--icons --group-directories-first"
description = "List directory contents with icons and directories first."
tags = ["file", "navigation"]
shells = { all = true }

[[aliases]]
key = "ll"
dependency = "eza"
command = "-alF --icons --group-directories-first"
description = "List all files with detailed view."
tags = ["file", "navigation"]
shells = { all = true }

[[aliases]]
key = "l"
dependency = "eza"
command = "-a --icons --group-directories-first"
description = "List all files including hidden ones."
tags = ["file", "navigation"]
shells = { all = true }

[[aliases]]
key = "tree"
dependency = "eza"
command = "--tree --icons"
description = "List files in a tree view."
tags = ["file", "navigation"]
shells = { all = true }

[[aliases]]
key = "cat"
dependency = "bat"
command = "--style=plain --paging=never"
description = "Concatenate and display files with syntax highlighting."
tags = ["file", "utility"]
shells = { all = true }

[[aliases]]
key = "nvim"
dependency = "neovim"
command = ""
description = "Launch Neovim."
tags = ["editor"]
shells = { all = true }

[[aliases]]
key = "grep"
dependency = "ripgrep"
command = ""
description = "Search for patterns in files."
tags = ["search", "utility"]
shells = { all = true }

[[aliases]]
key = "find"
dependency = "fd"
command = ""
description = "Find files and directories."
tags = ["search", "file"]
shells = { all = true }

[[aliases]]
key = "top"
dependency = "htop"
command = ""
description = "Display dynamic real-time information about running processes."
tags = ["system", "monitoring"]
shells = { all = true }

[[aliases]]
key = "df"
dependency = "duf"
command = ""
description = "Disk usage and space analyzer."
tags = ["system", "utility"]
shells = { all = true }

[[aliases]]
key = "du"
dependency = "ncdu"
command = ""
description = "Disk usage analyzer with an ncurses interface."
tags = ["system", "utility"]
shells = { all = true }

[[aliases]]
key = "ping"
dependency = "prettyping"
command = ""
description = "Ping a host with pretty output."
tags = ["network", "utility"]
shells = { all = true }

[[aliases]]
key = "watch"
dependency = "viddy"
command = ""
description = "Monitor the output of a program every few seconds."
tags = ["utility", "monitoring"]
shells = { all = true }

[[aliases]]
key = "sudoe"
command = "sudo -E -s"
description = "Run a command with elevated privileges while preserving the environment."
tags = ["system", "utility"]
shells = { all = true }

[[aliases]]
key = "tb"
command = "nc termbin.com 9999"
description = "Paste text to termbin.com."
tags = ["network", "utility"]
shells = { all = true }

[[aliases]]
key = "gitlog"
command = """
git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'
"""
description = "Show git commit history as a graph."
tags = ["git", "utility"]
shells = { all = true }

[[aliases]]
key = "k"
dependency = "kubectl"
command = ""
description = "Alias for kubectl."
tags = ["kubernetes", "utility"]
shells = { all = true }

[[aliases]]
key = "rh1"
command = "nix run .#homeConfigurations.$(whoami)@$(hostname).activationPackage && exec zsh"
description = "Apply home configuration changes and restart shell."
tags = ["system", "nix"]
shells = { zsh = true }

[[aliases]]
key = "fzf-history"
dependency = "fzf"
command = "$(history | fzf --tac --tiebreak=index | sed 's/ *[0-9]* *//')"
description = "Fuzzy search command history"
tags = ["utility", "search"]
shells = { zsh = true, bash = true }

[[aliases]]
key = "weather"
command = "curl wttr.in"
description = "Get weather information"
tags = ["utility", "network"]
shells = { all = true }
condition = "command -v curl >/dev/null 2>&1"

[[aliases]]
key = "zsh-only"
command = "echo 'This is a ZSH-only alias'"
description = "An example of a ZSH-only alias"
tags = ["example"]
shells = { zsh = true, bash = false, fish = false }

[[aliases]]
key = "bash-fish"
command = "echo 'This alias works in Bash and Fish'"
description = "An example of an alias for Bash and Fish"
tags = ["example"]
shells = { zsh = false, bash = true, fish = true }