import = ["~/.config/alacritty/themes/material_deep_ocean.toml"]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 10, y = 10 }
dynamic_padding = false
decorations = "full"
opacity = 0.99
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
option_as_alt = "Both"                    # NOTE: Needed for macOS

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = "None"
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[shell]
program = "/bin/zsh"
args = ["--login"]

[mouse]
hide_when_typing = false

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
