authorized_keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEXHjv1eLnnOF31FhCTAC/7LG7hSyyILzx/+ZgbvFhl7 geoffrey@artemis",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIITvBraRmM6IvQFt8VUHRx9hZ5DZVkPX3ORlfVqGa05z geoffrey@apollo",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN4Uy9fE/YF8/puhUOwOcHKqDzDW75zt9DndypPEhQaG geoffrey@pioneer",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN5fIudzRgRdB5m1Mh82hn1q239LT5UVRchin/CkdUuX geoffrey@voyager",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPnUdtmYcFJ0elvD2eXLvUX9InCF+CYK7MVOuzog7i98 geoffrey@cassini",
]

trusted_public_keys = [
  "builder-name:4w+NIGfO2WFJ6xKs4JaPoiUcxjm4YDG8ycLt3M67uBA=",
]
