keys: null
creation_rules:
- path_regex: secrets/default.yaml
  key_groups:
  - age:
    - age10nd9h4mh8vuq7h29karutjw6227g26uuztuut82p08sdc2vel4gqr4c62e
    - age1rw2gs2s2qfvvqt7c2nls758xvta4qxphy980jz7apt3vrl0gxdvqxfplrv
    - age14hqjh7pas08vlyuyppdfuc03yn94mpt4ld6zw293gkvnceduzfcsvmd2lf
