keys: null
creation_rules:
- path_regex: secrets/default.yaml
  key_groups:
  - age:
    - age10nd9h4mh8vuq7h29karutjw6227g26uuztuut82p08sdc2vel4gqr4c62e
    - age1yp4pf2z77snwkay35xjtcjs2c5u3d0c3fdkllkkk8c04yxs3vq2q7zdxr5
