keys: null
creation_rules:
  - path_regex: secrets/default.yaml
    key_groups:
      - age:
          - age10nd9h4mh8vuq7h29karutjw6227g26uuztuut82p08sdc2vel4gqr4c62e
          - age1rw2gs2s2qfvvqt7c2nls758xvta4qxphy980jz7apt3vrl0gxdvqxfplrv
          - age1a9lryzapql62vy05w9twp3kx98e4yrr8re5lu8hpgca3ccl2ns7q4yqz7r
          - age1qhdnzdutndxnmd074p736qwznwp8683zhs6nrn7qs8ucmnel2qpsrase8c
          - age14hqjh7pas08vlyuyppdfuc03yn94mpt4ld6zw293gkvnceduzfcsvmd2lf
          - age1jjc5zrcvex4r8tusuvwv00tk6srnerayle07unphz7kq2jlzm39qc52wdz
          - age1z09vrs2ketcn244l43fjxgzuu22yp0q0tpkmh3s2grlqn8jgypeqgnnf9f
