[flake]
name = "my-flake"
version = "0.1.0"
description = "Nix flake for managing SOPS and SSH keys"

[keys]
ssh = [
    "id_ed25519",
    "id_ed25519.pub",
    "id_ed25519_agenix",
    "id_ed25519_agenix.pub"
]

[sops]
age = true
from-ssh = "id_ed25519"

#[hosts.apollo]