---
- name: Terminal setup and updates for Linux, macOS, and Windows
  hosts: localhost
  become: no  # Changed to 'no' to avoid running as root by default

  vars_files:
    - ansible/vars/main.yml

  pre_tasks:
    - name: Set OS family fact
      set_fact:
        os_family_lower: "{{ ansible_os_family | lower }}"
      tags: [ setup, update ]

    - name: Print OS family
      debug:
        var: os_family_lower
      tags: [ setup, update ]

    - name: Include OS-specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "ansible/vars/{{ os_family_lower }}.yml"
            - "ansible/vars/default.yml"
          paths:
            - "{{ playbook_dir }}"
      ignore_errors: yes
      tags: [ setup, update ]

  tasks:
    - name: Setup directory structure and backups
      import_tasks: ansible/tasks/setup_directories.yml
      tags: [ setup, update ]

    - name: Update configurations
      import_tasks: ansible/tasks/update_configs.yml
      tags: [ update ]

    - name: Install and update packages
      import_tasks: ansible/tasks/packages.yml
      tags: [ setup, update ]

    - name: Update development tools
      import_tasks: ansible/tasks/dev_tools.yml
      tags: [ update ]

    - name: Setup keybindings
      import_tasks: ansible/tasks/keybindings.yml
      tags: [ setup ]

    - name: Confirm installation complete
      debug:
        msg: |
          Installation completed successfully! Please restart your terminal for changes to take effect.
          On Linux/macOS, use 'source ~/.bashrc' or 'source ~/.zshrc'.
          On Windows, use 'refreshenv' in Command Prompt or '& $PROFILE' in PowerShell.
      tags: [ setup, update ]