[package]
name = "nixus"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.4"
dialoguer = "0.11.0"
console = "0.15.8"
regex = "1.10.6"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
spinners = "4.1.1"

