[basic_controls]
description = "Basic window manager controls"
bindings = {
  "super + Return" = "alacritty",
  "super + @space" = "rofi -show drun",
  "super + Escape" = "pkill -USR1 -x sxhkd",
  "super + alt + {q,r}" = "bspc {quit,wm -r}",
  "super + {_,shift + }w" = "bspc node -{c,k}"
}

[window_state]
description = "Window state and flags"
bindings = {
  "super + {t,shift + t,s,f}" = "bspc node -t {tiled,pseudo_tiled,floating,fullscreen}",
  "super + ctrl + {m,x,y,z}" = "bspc node -g {marked,locked,sticky,private}"
}

[focus_and_swap]
description = "Focus and swap windows"
bindings = {
  "super + {_,shift + }{h,j,k,l}" = "bspc node -{f,s} {west,south,north,east}",
  "super + {p,b,comma,period}" = "bspc node -f @{parent,brother,first,second}",
  "super + {_,shift + }n" = "bspc node -f {next,prev}.local",
  "super + {less,greater}" = "bspc desktop -f {prev,next}.local",
  "alt + {_,shift + }Tab" = "bspc {node,desktop} -f last",
  "super + {o,i}" = "bspc wm -h off; bspc node {older,newer} -f; bspc wm -h on"
}

[preselect]
description = "Preselect window placement"
bindings = {
  "super + ctrl + {h,j,k,l}" = "bspc node -p {west,south,north,east}",
  "super + ctrl + {1-9}" = "bspc node -o 0.{1-9}",
  "super + ctrl + space" = "bspc node -p cancel",
  "super + ctrl + shift + space" = "bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel"
}

[move_and_resize]
description = "Move and resize windows"
bindings = {
  "super + alt + {h,j,k,l}" = "bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}",
  "super + alt + shift + {h,j,k,l}" = "bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}",
  "super + {Left,Down,Up,Right}" = "bspc node -v {-20 0,0 20,0 -20,20 0}"
}

[desktop_management]
description = "Manage desktops and monitors"
bindings = {
  "super + {_,shift + }{1-9,0}" = "bspc {desktop -f,node -d} '^{1-9,10}'",
  "super + ctrl + {1-9,0}" = "bspc desktop -s '^{1-9,10}' --follow",
  "super + ctrl + shift + {1-9,0}" = "bspc desktop -m '^{1-9,10}' --follow"
}

[scratchpad]
description = "Scratchpad management"
bindings = {
  "super + minus" = "scratchpad",
  "super + shift + minus" = "scratchpad -m"
}

[media_controls]
description = "Volume and brightness controls"
bindings = {
  "XF86AudioRaiseVolume" = "pactl set-sink-volume @DEFAULT_SINK@ +5%",
  "XF86AudioLowerVolume" = "pactl set-sink-volume @DEFAULT_SINK@ -5%",
  "XF86AudioMute" = "pactl set-sink-mute @DEFAULT_SINK@ toggle",
  "XF86MonBrightnessUp" = "brightnessctl set +10%",
  "XF86MonBrightnessDown" = "brightnessctl set 10%-"
}

[screenshot]
description = "Screenshot controls"
bindings = {
  "Print" = "maim -s | xclip -selection clipboard -t image/png",
  "shift + Print" = "maim | xclip -selection clipboard -t image/png"
}

[application_shortcuts]
description = "Quick launch applications"
bindings = {
  "super + e" = "nautilus",
  "super + b" = "firefox"
}

[polybar_controls]
description = "Polybar controls"
bindings = {
  "super + p" = "polybar-msg cmd toggle",
  "super + shift + p" = "killall polybar; polybar main &"
}
