repos:
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
        name: nixfmt-rfc-style
        args: [ --in-place ]
        files: \.nix$

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        name: beautysh
        args: [ --indent-size=2, --force-function-style=fnpar ]
        types: [ shell ]