repos:
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
        name: nixfmt-rfc-style
        args: [ ]
        files: \.nix$

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.4
    hooks:
      - id: commitizen
        stages: [ commit-msg ]