repos:
  - repo: https://github.com/NixOS/nixfmt
    rev: v0.6.0
    hooks:
      - id: nixfmt
        name: nixfmt-rfc-style
        files: \.nix$
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.4
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: rust-fmt
        files: \.rs$
