---
- name: Update Rust
  shell: rustup update

- name: Update Zellij
  shell: cargo install zellij

- name: Update Neovim plugins
  shell: |
    nvim --headless +"if exists(':PlugUpdate') | PlugUpdate | else | echo 'vim-plug not installed' | endif" +qall
    nvim --headless +"if exists(':PlugUpgrade') | PlugUpgrade | else | echo 'vim-plug not installed' | endif" +qall
    nvim --headless +"if exists(':TSUpdate') | TSUpdate | else | echo 'Treesitter not installed' | endif" +qall
  when: ansible_os_family != 'Windows'