---
- name: Setup keybinding (Linux)
  shell: |
    for i in "${!KEYBINDINGS_LINUX[@]}"; do
      KEYBINDING="{{ item }}"
      binding=$(echo $KEYBINDING | cut -d':' -f1)
      name=$(echo $KEYBINDING | cut -d':' -f2)
      command=$(echo $KEYBINDING | cut -d':' -f3)
      keybinding_path="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom$i/"
      gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$keybinding_path name "$name"
      gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$keybinding_path command "$command"
      gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$keybinding_path binding "$binding"
    done
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "[$(printf "'%s', " "${keybinding_paths[@]}")]"
  loop: "{{ keybindings_linux }}"
  when: ansible_os_family == "Linux"

- name: Setup keybinding (macOS)
  shell: |
    binding=$(echo {{ item }} | cut -d':' -f1)
    name=$(echo {{ item }} | cut -d':' -f2)
    defaults write -g NSUserKeyEquivalents -dict-add "$name" "$binding"
  loop: "{{ keybindings_macos }}"
  when: ansible_os_family == "Darwin"