---
- name: Install common packages (Debian/Ubuntu)
  apt:
    name: "{{ packages_common + packages_specific }}"
    state: latest
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Add Alacritty PPA (Ubuntu)
  apt_repository:
    repo: ppa:aslatter/ppa
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Alacritty (Ubuntu)
  apt:
    name: alacritty
    state: latest
    update_cache: yes
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Install common packages (Fedora)
  dnf:
    name: "{{ packages_common + packages_specific + ['alacritty'] }}"
    state: latest
  become: yes
  when: ansible_distribution == "Fedora"

- name: Install common packages (CentOS)
  yum:
    name: "{{ packages_common + packages_specific }}"
    state: latest
  become: yes
  when: ansible_distribution == "CentOS"

- name: Install Alacritty from source (CentOS)
  block:
    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install Alacritty dependencies
      yum:
        name:
          - cmake
          - freetype-devel
          - fontconfig-devel
          - libxcb-devel
    - name: Clone Alacritty repository
      git:
        repo: 'https://github.com/alacritty/alacritty.git'
        dest: /tmp/alacritty
    - name: Build and install Alacritty
      shell: |
        cd /tmp/alacritty
        cargo build --release
        cp target/release/alacritty /usr/local/bin/
  become: yes
  when: ansible_distribution == "CentOS"

- name: Install or Update packages (macOS)
  homebrew:
    name: "{{ packages_macos }}"
    state: latest
    update_homebrew: yes
  when: ansible_os_family == "Darwin"

- name: Install or Update packages (Windows)
  win_chocolatey:
    name: "{{ packages_windows }}"
    state: latest
  when: ansible_os_family == "Windows"