
---
- name: Update repository
  git:
    repo: "{{ repo_dir }}"
    dest: "{{ repo_dir }}"
    update: yes

- name: Update configurations
  copy:
    src: "{{ repo_dir }}/config/{{ item }}/"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}/"
    remote_src: yes
  loop: [ alacritty, zellij, nvim, nushell ]
  when: ansible_os_family != 'Windows'

- name: Fix permissions for configuration files
  file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_env.USER }}"
    group: "staff"
    mode: '0755'
  loop: [ alacritty, zellij, nvim, nushell ]
  when: ansible_os_family == 'Darwin'  # This ensures it only runs on macOS
