hello: ENC[AES256_GCM,data:ft7srzBPylRa49/u6JWJ/cjXu3BVi7ukNNmFk+2ZrDbwagpf1Zl+ou5y6Xv2JUrGYa2ZIlopfw==,iv:3kVp4km/CoCISSmhGeXvExNwS6COnae04oLIQshWNRY=,tag:1OiyOzF++tfZaUj7fZtP5A==,type:str]
example_key: ENC[AES256_GCM,data:QScqvQzLOKb/fd0tsQ==,iv:kjA3o8Yy7e2D/lohkPgVYPKvAM+V0UC3ljTFXtvjKTE=,tag:vd1UHEn7gc7oyacbhNZ1uA==,type:str]
#ENC[AES256_GCM,data:bbiWlc9VcxXVsDOwjkl2aMJWNL/yd2DVJ0GvyrILFI8oYiCBr2ojmn9iO+w=,iv:PZ3Ot7G6GWMbPgchjVSIP9HfKv7RcFpI8ZnvIwvYXwU=,tag:Fk3YFxB6rymnZ1P426kY8Q==,type:comment]
#ENC[AES256_GCM,data:+gdsHvm3SWgoJS2ThaiHRvs50/+sq2R8JQ==,iv:C5yrYxR0yo2DhkzuTIYv/qU05g0l+pnqLHKleAcz0zk=,tag:CBo+TAed5S3SNYbKCwj9fg==,type:comment]
github-token: ENC[AES256_GCM,data:wdYXCm1ChcW39pP4PQDZdiccytOFxrw2k3oLUkkbUgM8wB89hr5K2BcWpmjIhH+7cm1pUjxJ9gLdftPpUvYEBESTiMnK++5exUw5X08GbBjwGfMGe9X6ZrwcX/Bx,iv:sv3VW99oiCIGNsbx/qi5oyD1si6ssQTHPLqd7IEOHK8=,tag:B1QMpNKj48TDQdVU1f+GTA==,type:str]
openai-api-key: ENC[AES256_GCM,data:l1itdOYYC81yDdkIeaP91vzTEearHW5GsFbMzmG56mD5Yv61WvdrUGo4/Z6cy611owTB8Xi2egHGOybLK15R8prd0ItvUNQB8eWXv/YFAweQ979Htv5cWdW3OvA/KiA=,iv:MvoIWB//uWphqNUsfqpPbKMwf9EO6KCtTa1ldU9/yCQ=,tag:NT29JTVOPusoC1IVEwwAfw==,type:str]
tailscale-auth-key-value: ENC[AES256_GCM,data:pNEWewIYS7jX80f0+ypFpi0FJfWaUWyJgBL/48zzRmY5vlGucpPMotH7XF6Zm/02tpP4T+kAMJ27hJLv6g==,iv:M0I1VuePyLTRjKM5GWpBzSjO2v+Px929dw0E1q2cBvU=,tag:FQDuffFvxGjekIeaR3PCWA==,type:str]
tailscale-auth-key:
    env_key: ENC[AES256_GCM,data://7m/N7RNluPQdSvURI2gkZU,iv:OzexAONw9gS+1exEI2iRKxWK/Ow1Q6RCxjojbRqu6SQ=,tag:NgnuhAZEOCVdhXgyAYRg7A==,type:str]
    value: ENC[AES256_GCM,data:8XCG/x2dL+j1f9L1bNTSq2dnxUazsWMHVaaQuULLuIEEWa4CT9QreEOWKXicuehy0StmPUuMDDN2FyqAtA==,iv:KbHaN9nDJ0uRfp7XHXyXuzpiq8oF5x+ueVMBIt2XmUQ=,tag:ksQAk3fErIm3i1Ldzj9n1A==,type:str]
    description: ENC[AES256_GCM,data:uPArnMqj1h/zqMdSTKE1D1Fo0g==,iv:Sb2gfrmTMpJ/AT3Fv4BgNwb5CKr4I7+0JuCvu8WI9S4=,tag:eXsqhhJtoecSHzcmFbc79Q==,type:str]
    id: ENC[AES256_GCM,data:r5mnshSB7S6qgH4JXV7vuG4=,iv:bj7L5dXRSXt50090D7Vd8CzYTLIh8aEgT8xpqjPIIww=,tag:zH72Ogo7jjJi2p+PUAq9xQ==,type:str]
    type: ENC[AES256_GCM,data:WJf0DDuYFaY=,iv:P6CaY4YYMR4k9ziX05YmGZMLfm+NzT1IC+x9n9aUYB4=,tag:TZWsh07evbmQkqc9LxY1vg==,type:str]
    expires: ENC[AES256_GCM,data:rkRqdkF6OC+oOQTOHIParJOOk9mj+7wp,iv:hW19cKHsfvqNQ4HdHrRzO4KCyjd2Fsv192XtNV+d3Hk=,tag:yxdkipVA5vQ0Uxyy9a4MBQ==,type:str]
    created: ENC[AES256_GCM,data:581i0nS6m2Klx1FVGWGJuH0kdUYYz2jQ,iv:ijt1NySwGkmOcqoayhJ+jEn8uvtNja4FreI/pcChGuU=,tag:9fuAFBfeqcprAZqaZrwH0g==,type:str]
cachix-auth-token-value: ENC[AES256_GCM,data:OrcmrZUKupt72Aiv+/JubTl87u/E9oh44vA2Vh+cczR6jmqy+AV42efJQtLtRS7FAze7TD/f+OyDJiElpoBEDiSLeeIvrXoBRRy5aDnsdw7Yo696KwBHFRvKiEZq1n+Uk4AV3um90wyiqQW8tPzSvJcLTy4s6zHp3URo6DSc567jZ5ZvK8ACG8zGgX9CxliBybkCh1s=,iv:0Cf1Otpq7eVigU+FxRFdTNqZFTFA/IbBq53zfqdVuWs=,tag:utOsBfL9NFZ1359RLDFADQ==,type:str]
cachix-auth-token:
    env_key: ENC[AES256_GCM,data:oRU+5Z/7tgJnyorPmWPZqoc=,iv:ffm7SJLIbRxKk+lD1QMMdGoBvibZwIIhd7PPbZcp8to=,tag:zKIodQ8Nw50+tTgg9M+LoA==,type:str]
    value: ENC[AES256_GCM,data:7MhQxO7RvmPCkZLPE+yi69f6RDI6B8Jd2jJEDxcDPWWIxDwCH1+Sy0bZcsdO9uW4I2bXj9NKxnv2aiIIYE5wHg7kqg2jbokoAu2rqWAUcVN7CFOKA+pukZT298EsIVeQxUPXMSiKefVgr92hop/cuqO76zMtiApI5Y+fCt7WW67rF3oOcACWXBdTp/xByr85iBJd7M4=,iv:QP8U9Edc0Rv2QeYpORGxElXcrgRQ9GSuSQzQdVeJN8o=,tag:p05Q3ws2a9mbmXvZr7APgQ==,type:str]
    description: ENC[AES256_GCM,data:SBxAjaX8ARYiOIiU6ZiAEw0dEq1Shw==,iv:blzrBuuTmQtQRYeHxLKjmibzvw95rUmI4IAY5oRJJNc=,tag:RJUBly35ooR+ilPrVbH7Nw==,type:str]
    permission:
        read: ENC[AES256_GCM,data:qddNaQ==,iv:JhI66D6ZeAhfRcWjuDdqbt5e6XlMmyQt/+2/hkzydgE=,tag:viQUuGGPL4Pjp7P2zxFcxQ==,type:bool]
        write: ENC[AES256_GCM,data:XbmfVg==,iv:N5Lo4cRrbtWJIy789PRQV2jt9UfLl2OZDKBn8Wv3jl4=,tag:YcH04Bqx4iPDrXQsAAYfbA==,type:bool]
    created: ENC[AES256_GCM,data:KmIHFhk9LK/yfirSnP/i+XjV8hbKbAmJ,iv:Jr1AT/lW5dvaRRSxnINcOl8jJq1EoJrBOZqpPr1mlpg=,tag:Ozrx4Is0fhVc10fxKtMS+g==,type:str]
    expires: ENC[AES256_GCM,data:nd8rYM9NO3GbNd6OzYDSNCFBSky+bW+1,iv:xy9HNcT07B5juQu+9q7mbBgajDvRyteB7HlTFxBE2Qo=,tag:b96L+XMrEk6JjbkKx1Yzlw==,type:str]
    action: ENC[AES256_GCM,data:vwMzA7B79MYrra9iI28ADi+hO7ql,iv:oGv+nLqHaJBxoWWfU4rrf7ZGh9nK/8Z/zTASS9f4T4o=,tag:aV7hq5yGnJMoChyieMN0zQ==,type:str]
example_array:
    - ENC[AES256_GCM,data:iYJF3nRzYy2ZTtRlp8Y=,iv:NBzMM5+tneq9cBJo7IKjOzqwny6ISA406Zk55pbTAfc=,tag:UG4ktZnsQ/n9P54Sv2IxVw==,type:str]
    - ENC[AES256_GCM,data:iogIW+XPnQwTFCK8P8Y=,iv:+ISxKnupIL2D4M1RGHtrbv0l+YYwfmP4oEpgzVXNH8o=,tag:16GAPe1v+B2vnNcsQFsvIw==,type:str]
example_number: ENC[AES256_GCM,data:oN4M9NtY7ecuhg==,iv:u0IJ6R5JhYKy1UayUX8fTpP/b0kJbZZAOB+sUGxvunY=,tag:Q9BzuI5o/BLja+Hq3ZbtXg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:/r609g==,iv:ZMa6fQnjl3oN88VePwjUKeFJ167nJnLMeSHb+MntTg0=,tag:8cGS08hkLFNC2TXLLojLFg==,type:bool]
    - ENC[AES256_GCM,data:eDgnO5A=,iv:2MHmUXHq+R5CfBtvL4NsLTVYJPKugVBAIIZOJB0W7cc=,tag:zjSel7S9PL2uhHzI4cCB9g==,type:bool]
wireguard:
    artemis:
        name: ENC[AES256_GCM,data:whZhCpd+IQ==,iv:7qfIUWu6zMiwK7F4lXve6wRf8snW1upCCtoY92NY2Yw=,tag:3kxmkCGKTKd2Fu12BIy+yg==,type:str]
        public_key: ENC[AES256_GCM,data:mOOskn/RqPNbmFuWg8SQV/HNt/mHqr1ZbxWx9fyZzNy4U7TcT/nyVEUtSfk=,iv:fSSJ86FmiDGFIhiJTs3/4VueAiQpOfJjinBqRb3qcQ4=,tag:oxM4j+3nm9rV4mucG32aKQ==,type:str]
        allowed_ips: ENC[AES256_GCM,data:Ta1X2kupXyP5,iv:ZcYf909sgju0SRYRlmjNiitoJYY/VyHWu0B04PIMudc=,tag:UIqDvJtOP5TVq7o+hnG2bg==,type:str]
        endpoint: ENC[AES256_GCM,data:fEQZ95fYjLuSa72o/YPTofn3qHU=,iv:u3p+fV0c8GmRkfsr8I6PCXW1zhRPOVuob2JHFZ12hUc=,tag:SsC8H3YhOqqDZ+czQqJpXw==,type:str]
    apollo:
        name: ENC[AES256_GCM,data:KqQaVWkU,iv:jnTL3ScheoCsuqrce6SDBsWtRlD0T3NpBDGnwsURlXs=,tag:VIK2EYytAb6FbdzUw8MhFg==,type:str]
        public_key: ENC[AES256_GCM,data:tTQab1rUjkQWHfV8JkIcOW+O3IwBdrYsaNYtWBaLxqnjJ/xHIZ9Xbqkn1nM=,iv:wlRMPxABGsrgEcqlcNoE9TbhkgHlsc9/2FTac3iPbUQ=,tag:/XB5MeH3ilSny2y8TZCmmg==,type:str]
        allowed_ips: ENC[AES256_GCM,data:iV0KFxS+mB2a,iv:7EWDgN+6owILTD7QSeM+bXBG9kVbSrcO0imGaSkRiQE=,tag:u4RZybHEO5lbUa4ehmBDYg==,type:str]
        endpoint: ENC[AES256_GCM,data:y5I5x2rnqfJtJwxJiw==,iv:NqgRP4jPFghwVSpf5QsSCTDqGYnXgLpQWJGL7Uu+n0c=,tag:UqJo9RMWOMciCk8clUOSbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nd9h4mh8vuq7h29karutjw6227g26uuztuut82p08sdc2vel4gqr4c62e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOGo5YXQ3OEdwN0hXLzFR
            K05tRXIyazJpYlVzVHdERHFGOSs0RHFoRG1FCmhCWEJMTFBad3dDbFRsc08wK3RG
            MEpEZ0w3eGc1V21SSENwcXVXZzM2dTgKLS0tIEU1SkMvQ2l6djdzQ2lDUzJhd1hv
            ck55QTRjMGFhc0VtWC9pNUpLZGdWcjQKiXI8dvbNNzS/dio1bRjdKCVSOoClx38T
            co8JKKwu3eE5a55NsElevhy7kY7eEU6cqASAVrtgZXCoFKVmVHvaTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rw2gs2s2qfvvqt7c2nls758xvta4qxphy980jz7apt3vrl0gxdvqxfplrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNFFqNys5YitFN2lUS3g5
            Rnc3L2lKWm1hTkw5dDBPVUpKd2R4cGw2Wmc0CmZaM2VMdFpaM1dTN3JUak53dzY3
            SmM5Z0F2Zmk4MlBPQ1VLNmhla281emcKLS0tIGFMNTdoQW1vbVEvekRtamhYMXBV
            RDFXa2VzbzBqVVVnUm1mUUV5blZqMTAKtvcjVQ+r1w2qoUBwKVwb5ttl7SdXOUsf
            JVazRQ1dpGh4g+5bCQPYirxme1+vrKgPfWO0wNtU6+eGzURg/UnPmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9lryzapql62vy05w9twp3kx98e4yrr8re5lu8hpgca3ccl2ns7q4yqz7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZGxRQ25HRkw2VDluZktu
            QXVXemRwU0lCUUFURUQ3MzMxSmE3WnhrdmdVCmpuOFpFeWNmMEd2UnFvOWg3L2ky
            Ny9PemNJUzIwVkV4NXFpYXQwOXBRMWsKLS0tIDNsRnAvc3JDTDRIWFE3RzV4djkr
            dUhiSU9UY3RIVmdLdDFEcmtIYVQ4S2MKMHt2w/MnsY46wS16sW3sX/ePrap3Nq6R
            Nlk+w250VOMBlWtTZXjD+leOWeic8d4ETu/AIEfpMn80jDS/OyiZRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qhdnzdutndxnmd074p736qwznwp8683zhs6nrn7qs8ucmnel2qpsrase8c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN3RyRnRscm1aRllWdldX
            dTdHL2thYlRKNEMvenhqR1Zobkx1SkdROWpRCm9oVVJSYWllWEVBNXNKRU1RcFBn
            S0VxWk43UlRhc3RVcDNBYXduTHI1WVUKLS0tIDQzUzNNWXgzN1RjSDkreDZ5c2RJ
            cnJ2enAwN0tZZmlVMGRST2dTR205ODQKmeg5YmHrGBvDmLV8KTgVVd7ibJXG3Ncc
            3N5yRpYcYrEAmHI9mdzZKGW1oqanAj/QplqVA+/9DOitunxmyqXrAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14hqjh7pas08vlyuyppdfuc03yn94mpt4ld6zw293gkvnceduzfcsvmd2lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmenNVOVhYcHIwbXFWMUtm
            aFJTMkNObnZvK0Y3Q0RiMlhtalhnWGpSOFFJClNnTEhFcWRGNDhLSzQ1VUJ1cGpU
            aC9KdkxyanJQWTlTdDdQZjZSS0RCK1UKLS0tIEJaVUdiZGFmRm9vWU1SOHN0aVM2
            UVhLaVd4TXdOeGNtL2xzSk1NT1lobFUKEpgyH66vQDzNM3Zzscz9lXoIsMLSak1v
            PSxm7AJ4fkMe4ihjLSAw3asXPLTDQ0l5YAcqM70ElLPcEpUa0ZeUrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjc5zrcvex4r8tusuvwv00tk6srnerayle07unphz7kq2jlzm39qc52wdz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSkFyT0VuN0EzT2g0VjA1
            b29SMUFJNXA2NFBBeEEraTR4eDYwZjFLY2pZClVQQTIyVWJTNU50U1A0RkRGcG5D
            MGplMTBWZkd2OWlFREFuejh1bXFPK28KLS0tIEQxOGVtTGN0SEdWREF6Y1VRL2p2
            ZTl4a3B3cnJLWnN4M2s2dVJOYkdJQTgKI+NNZmUImGdmV11jYTBGysuHooLSZPTS
            kzx5qvcSPlwr66tpvn8Qdk2Jdw2zDUY/OiaiSjhXR1RSUf43HX6xTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T14:21:11Z"
    mac: ENC[AES256_GCM,data:2KI7g2oP5ZGmtnRQCMa5gDzDyaConBZrzxV8AdUFwsag31x6NSRtOAoya7AGru+/+k5+6igR74Y/03NSQi6q7/hBULBm2vMaelCSZAingGj84T1N4MNQV6vgXHzDxVJPEznhXheCsBhdbfcOlxjT2KzWBCqMPugU0VvuwL8a2MA=,iv:xFRNJjjz+/YP32kRTC8IQKiWusnWCVbdeXeUgdH75RY=,tag:FqXf5lOOa+XdOb2FRwpvhA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
