#ENC[AES256_GCM,data:bbiWlc9VcxXVsDOwjkl2aMJWNL/yd2DVJ0GvyrILFI8oYiCBr2ojmn9iO+w=,iv:PZ3Ot7G6GWMbPgchjVSIP9HfKv7RcFpI8ZnvIwvYXwU=,tag:Fk3YFxB6rymnZ1P426kY8Q==,type:comment]
#ENC[AES256_GCM,data:+gdsHvm3SWgoJS2ThaiHRvs50/+sq2R8JQ==,iv:C5yrYxR0yo2DhkzuTIYv/qU05g0l+pnqLHKleAcz0zk=,tag:CBo+TAed5S3SNYbKCwj9fg==,type:comment]
github-token: ENC[AES256_GCM,data:wdYXCm1ChcW39pP4PQDZdiccytOFxrw2k3oLUkkbUgM8wB89hr5K2BcWpmjIhH+7cm1pUjxJ9gLdftPpUvYEBESTiMnK++5exUw5X08GbBjwGfMGe9X6ZrwcX/Bx,iv:sv3VW99oiCIGNsbx/qi5oyD1si6ssQTHPLqd7IEOHK8=,tag:B1QMpNKj48TDQdVU1f+GTA==,type:str]
openai-api-key: ENC[AES256_GCM,data:DY9jGGHiJAxzdCcTeBxEX31Yk7IpZzV1Ek0ZBXBbIA/67FYB6f2qvpVOo3ST/0ALRYbEwNBAugdAP0TTEA6NCazs1x7vZjOyON3opo0zZZf/xUnY0tQo2ZJ2Es0BEFTCn+tlHwqBl3mhsGrj5vMxm63esOhUNSBSBiwTlu9Fmlj5cl9v3wdZlQI0k39rh9vvhiYUstj2jKsz7aBbzqsbrS3glX4=,iv:3gbeudAZHSljnS269o02/9IN7b1Heum68JH+MCiGyP0=,tag:4gL7vGnDMbPIpQf5MsT2IA==,type:str]
openai-project-id: ENC[AES256_GCM,data:QXJRwySsMgCNy0X6ShW5nG/h6+b+QyBA27N7zoc=,iv:AcwK+R452IBZJVkF+lJxPuIn36+fOd4q/KyI8PELQKM=,tag:JSBiHmh+0GH5u+PC+UbS+Q==,type:str]
openai-organization: ENC[AES256_GCM,data:o9x1PFjff3yu4zTkuEGeHlzgzd++iNYNCGTcaQ==,iv:/hyZ8Ow7+fzr8VrNzQ+lQE5047YKiCFxBFUjckbRvjI=,tag:G6XWFtdDUrCCWYqyhQHeJg==,type:str]
email-password: ENC[AES256_GCM,data:yg7ipoghBxhZKP0o+I7Yvqgrnw==,iv:0bORLamJcNAEWzlOYQFWgSMSptvI8LsjxxM0OWnX/oE=,tag:a5NlWVaI/k/bzCryxAgZ5A==,type:str]
tailscale-auth-key-value: ENC[AES256_GCM,data:pNEWewIYS7jX80f0+ypFpi0FJfWaUWyJgBL/48zzRmY5vlGucpPMotH7XF6Zm/02tpP4T+kAMJ27hJLv6g==,iv:M0I1VuePyLTRjKM5GWpBzSjO2v+Px929dw0E1q2cBvU=,tag:FQDuffFvxGjekIeaR3PCWA==,type:str]
tailscale-auth-key:
    env_key: ENC[AES256_GCM,data://7m/N7RNluPQdSvURI2gkZU,iv:OzexAONw9gS+1exEI2iRKxWK/Ow1Q6RCxjojbRqu6SQ=,tag:NgnuhAZEOCVdhXgyAYRg7A==,type:str]
    value: ENC[AES256_GCM,data:8XCG/x2dL+j1f9L1bNTSq2dnxUazsWMHVaaQuULLuIEEWa4CT9QreEOWKXicuehy0StmPUuMDDN2FyqAtA==,iv:KbHaN9nDJ0uRfp7XHXyXuzpiq8oF5x+ueVMBIt2XmUQ=,tag:ksQAk3fErIm3i1Ldzj9n1A==,type:str]
    description: ENC[AES256_GCM,data:uPArnMqj1h/zqMdSTKE1D1Fo0g==,iv:Sb2gfrmTMpJ/AT3Fv4BgNwb5CKr4I7+0JuCvu8WI9S4=,tag:eXsqhhJtoecSHzcmFbc79Q==,type:str]
    id: ENC[AES256_GCM,data:r5mnshSB7S6qgH4JXV7vuG4=,iv:bj7L5dXRSXt50090D7Vd8CzYTLIh8aEgT8xpqjPIIww=,tag:zH72Ogo7jjJi2p+PUAq9xQ==,type:str]
    type: ENC[AES256_GCM,data:WJf0DDuYFaY=,iv:P6CaY4YYMR4k9ziX05YmGZMLfm+NzT1IC+x9n9aUYB4=,tag:TZWsh07evbmQkqc9LxY1vg==,type:str]
    expires: ENC[AES256_GCM,data:rkRqdkF6OC+oOQTOHIParJOOk9mj+7wp,iv:hW19cKHsfvqNQ4HdHrRzO4KCyjd2Fsv192XtNV+d3Hk=,tag:yxdkipVA5vQ0Uxyy9a4MBQ==,type:str]
    created: ENC[AES256_GCM,data:581i0nS6m2Klx1FVGWGJuH0kdUYYz2jQ,iv:ijt1NySwGkmOcqoayhJ+jEn8uvtNja4FreI/pcChGuU=,tag:9fuAFBfeqcprAZqaZrwH0g==,type:str]
cachix-auth-token-value: ENC[AES256_GCM,data:OrcmrZUKupt72Aiv+/JubTl87u/E9oh44vA2Vh+cczR6jmqy+AV42efJQtLtRS7FAze7TD/f+OyDJiElpoBEDiSLeeIvrXoBRRy5aDnsdw7Yo696KwBHFRvKiEZq1n+Uk4AV3um90wyiqQW8tPzSvJcLTy4s6zHp3URo6DSc567jZ5ZvK8ACG8zGgX9CxliBybkCh1s=,iv:0Cf1Otpq7eVigU+FxRFdTNqZFTFA/IbBq53zfqdVuWs=,tag:utOsBfL9NFZ1359RLDFADQ==,type:str]
cachix-auth-token:
    env_key: ENC[AES256_GCM,data:oRU+5Z/7tgJnyorPmWPZqoc=,iv:ffm7SJLIbRxKk+lD1QMMdGoBvibZwIIhd7PPbZcp8to=,tag:zKIodQ8Nw50+tTgg9M+LoA==,type:str]
    value: ENC[AES256_GCM,data:7MhQxO7RvmPCkZLPE+yi69f6RDI6B8Jd2jJEDxcDPWWIxDwCH1+Sy0bZcsdO9uW4I2bXj9NKxnv2aiIIYE5wHg7kqg2jbokoAu2rqWAUcVN7CFOKA+pukZT298EsIVeQxUPXMSiKefVgr92hop/cuqO76zMtiApI5Y+fCt7WW67rF3oOcACWXBdTp/xByr85iBJd7M4=,iv:QP8U9Edc0Rv2QeYpORGxElXcrgRQ9GSuSQzQdVeJN8o=,tag:p05Q3ws2a9mbmXvZr7APgQ==,type:str]
    description: ENC[AES256_GCM,data:SBxAjaX8ARYiOIiU6ZiAEw0dEq1Shw==,iv:blzrBuuTmQtQRYeHxLKjmibzvw95rUmI4IAY5oRJJNc=,tag:RJUBly35ooR+ilPrVbH7Nw==,type:str]
    permission:
        read: ENC[AES256_GCM,data:qddNaQ==,iv:JhI66D6ZeAhfRcWjuDdqbt5e6XlMmyQt/+2/hkzydgE=,tag:viQUuGGPL4Pjp7P2zxFcxQ==,type:bool]
        write: ENC[AES256_GCM,data:XbmfVg==,iv:N5Lo4cRrbtWJIy789PRQV2jt9UfLl2OZDKBn8Wv3jl4=,tag:YcH04Bqx4iPDrXQsAAYfbA==,type:bool]
    created: ENC[AES256_GCM,data:KmIHFhk9LK/yfirSnP/i+XjV8hbKbAmJ,iv:Jr1AT/lW5dvaRRSxnINcOl8jJq1EoJrBOZqpPr1mlpg=,tag:Ozrx4Is0fhVc10fxKtMS+g==,type:str]
    expires: ENC[AES256_GCM,data:nd8rYM9NO3GbNd6OzYDSNCFBSky+bW+1,iv:xy9HNcT07B5juQu+9q7mbBgajDvRyteB7HlTFxBE2Qo=,tag:b96L+XMrEk6JjbkKx1Yzlw==,type:str]
    action: ENC[AES256_GCM,data:vwMzA7B79MYrra9iI28ADi+hO7ql,iv:oGv+nLqHaJBxoWWfU4rrf7ZGh9nK/8Z/zTASS9f4T4o=,tag:aV7hq5yGnJMoChyieMN0zQ==,type:str]
smb-secrets: ENC[AES256_GCM,data:M7xe8CzbIihjULi9NpCqPo+ZerS+6SxCHrPn1VGOcMPxLW5TfR8w+4rGI5r0LEinaKxu1waoGlvu,iv:b3eMuRvYgLGkjRf5PjEkXXDxSIwWHGLldW69t8tL9HQ=,tag:B1OIw0+Y292wyCavB+AxUA==,type:str]
wireless_secrets: ENC[AES256_GCM,data:eLR1yLhJRo/l1ZOL7lQgAKfvNDSKoOmaD7bgwlZ4X8bALp2zOdXIp0SmRDsY6FK/K6iHVYRlNyGwbLdbW6fL21cO3SHbXEkqsxylP7nZLMw=,iv:W3jMiL4hd55Emf+0I1lsAHb6nxZKDaeptnSCZyUT9XA=,tag:0DBDptG/WsniRxNf1jtGIA==,type:str]
wpa_supplicant_conf: ENC[AES256_GCM,data:JXP1n30BLFNF6IskfiptMMccoNyFgOQj+fM7jJfmrI+fGnzQJRGUB9rgezN2QVdtUMcQOltKjK5VO+Kv5dSGmQrjGv4tiHv9WEZjoNK9IfWRVk2RAwwMZYcSXGDqPBFxk8KqshxlohMfuzkMRfqLFbAUeL+4RkCaQXrdMBhLC8VR3HjAEhqizWcGhcTLXI4VHoBFu3UHNjetpvCFd4PeUXBQsqlEOgLSOoKL+VjkuLBlcIea002syw1UqVN6576jnb+i5givFc/MYCLFrVD7SzR+LxOL1d0YtigyM+362BNzKgjUyrOtaGZ4Wm8PkAqyoaQD2ItrUYMP1KF9o3f+azP9RnULCN0cGvZQWf8ppmYcvy1aVH2mcztCyo0DBDxFHhng0sUe8DDojZ84pacg4Lt319eOLOWfj5/JZXlZI1TFvU9npLMF2kYwQHPTLZu41PBTTuv0WP9tW9B+gxvDBRehIYrIPpQ08jVFtb2MXZD6N7Cy+C4T5SCOPfLRIm6eSHrqGfR+t4zC7M1erSiyadV9v6wxel8Euv7x+JLPKyxmn7E=,iv:QSz/HPRrtwmwI9SNqAVudnTWLSuQMVFKE/iro1P/b8c=,tag:MoBWnMx7RPSn6Mi39AWeYw==,type:str]
redshift:
    latitude: ENC[AES256_GCM,data:9XgxjV/QFzM=,iv:aS0HcCJ2hLXh9nLkKe1ZcJeYwZ0UxmqZ4ftTZ2lnQNo=,tag:z+skAQ9Mpshp7Fr6nu7N1g==,type:float]
    longitude: ENC[AES256_GCM,data:cU9UP2/Yeg==,iv:yR58yiWyeyCrrouV7OruclDEFQvGTcfC34TOyMlh948=,tag:Q9WSXepjUWcSg1JU8y+bGw==,type:float]
k3s-token: ENC[AES256_GCM,data:jts0Eu2nOk5+Xyny3QXLNrtMACipfBUPs5R/Eb8KinjwHHDq2W58Ld/b1JpFrG2IBPsR96pS4TSYcTLwXRJGhKUGpvPldlSZOkplB7v18CsyHvHDXJJnksk/GdGXPrWUPC5Sal5uEj1onlCM,iv:QCp9USw5Dz5ENqE0qBPGqPhkHAFbMwQV0J7+yfYRT6s=,tag:5KKSAdHZF86mgYRZFm7Nog==,type:str]
users:
    geoffrey:
        password: ENC[AES256_GCM,data:PGt7YUcqqJsUJgCA7G0F7qI58E4qt4QfGMijjE2cqQNOVE1gY5B9juA7TIX0o54twagPfh6FwJGt2/E6C4mSi0NR0yPctUlp4A==,iv:J6PZStrY8m9shi9rL5aS4MNYwhi2pEzDwfVyWF0rtT0=,tag:YiD2Ife5IaNY1dtS/NlgPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age173mhqrnhztgrrjc5vykz4hxmku7kplsherscym3ummxyg9dtf5vqqq72u2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxU24yRUdKWTRvWVYyK0ZS
            ck81TXA1Z29RdGVscWNpTEg5d0wzbXpwbERnCm4wTXVnWUxZQXQ2ajRJWWNyVGwx
            QUtnV0xvVDQ1NlA5MDBYUXFqVWpzR2cKLS0tIHB5TzJPRTc0SjZUbjVWZlQ2ajFJ
            ZXcwY2hTT0wxZFY4cDVzZ1V5dkNkdjAKrtm8VQEGc28lXEYuasVN7bNoLyQ7mF+2
            l15T9J5QFmHZP1WKXAEJFohCKlQCgf3Vo7x8kh5lHpz8l4cITko8lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdp9ndxywv48mapkkejujvzfqhxzyzp6s7kp42u7ynu6q5e8sqkqp0w7sv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSazY3N1g1SmFoVjNpRDdI
            N3NjaFFrejZvVTN1dHlVTTNHRS9zVjRmcVR3Ck1sV1BQY0hpd2JCazBqKytZM1VD
            SjNTR0QrNkZnSlphc3RaTmY0S05NcjgKLS0tIHUzTVREU3J3SUljSVB1am1ObDhQ
            SFRlZHNZVE03VUhqa3YxQUg2N2dxb2sKrh+yKqxBXsRoyY759CLilcrsSDtqJ4/M
            KlMeEqBo4oAUriNAq/qDXAI7M6KRav/+whfQxfB3CQlCO7/M5gIRew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tpj92c7aqe8df7g3qf58vzcyevx53vhap3qkrxa9calpdtp5vvmqrd0de7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdE4xRkp2S2FYaVBsOTJp
            djMvSnRQYlVHb3FLVFJnZHZtVDRTNi9TZURzCjBPUWdIeGw5R004YWxWZXl0SUs5
            RkRLMjFaMGdOUFlqMnhERFVqUzk2N2MKLS0tIGhQWGRXSW51dFI3ai9lMjlieDh1
            UWVSOEF4NjJibXVqU1lvcDlVSWtZVWcKBJEorEkopag5ooCwMmcwR0Z9Gp0zeXRG
            9k7KzqHb6QwLniCcrburfCQUZs0PQjQIBXE7Wmosv+XQNHBY40xxtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13sx384sda6z7lvg6arys4asl4j88t652y0r9km86n3xrsuh5hpzqndl9lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZkN0Wm9GaHhtd2FWcldV
            ZytuRHV1VTZ1MEQ0ZkYzMndZT0VXdGVqQ0JZCmV4U1YzOTE2Q0g4Ui9TOTNEanB4
            c094eW02WDhKcG1oMmlQbzc0MHEzbHcKLS0tIHhPb2F2RlJxZU9HK1EyMDVQd1VN
            OHFXWjFBdDJieU56YVg5VGpEakFOZ1UKVyuc2eppBIMaaBYpba/8uATksl2Ilnj+
            J9a9D7emSuQ3/ALrbfCEyblFXo8ZIzN2q3tGLCqYXoMwEWUha17PIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ahyztttw0jky84tzg5vzvhwvhy3c4ptw7zg4kv5jrn4ergjq2c3q4f76dv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY3A2QUUxU1V4aUtsS2Ro
            OHU4aW1qYzJIa1J5YjdFVGQ2ZWhqaW9wV3dnCkh4bXJ1dStNK1V5RkdicCtxbGt5
            TzRYZWxNcXlVcmxVTGxxL3RaZmdEb28KLS0tIFI0Zlh6UVlKcElPMHViOWlUcUMw
            Qk5PUk1ZK0ozbk52ZVpEeDBibVlnWGsKqJ9R/CsYlDdioUjJr20YBULS9O4Dw8hU
            zqOUcuXEBSN9woHKPL4rECT6wV24BVGNgAIpda3tDQ0bsE3A7YZ8nQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z09vrs2ketcn244l43fjxgzuu22yp0q0tpkmh3s2grlqn8jgypeqgnnf9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZXQxdVpKSi9iV21lR3Ev
            TGtWeWZ4bGpjbEFMTlE2SkdGdW1JMlVYcjFrCk5LVmpzS3dIS1pTYmZhM3orN3k0
            blhWaS9tZHBrUDhnM2NHUmMzazhJQ0kKLS0tIEwyTlZzRVVMWkV6YTRLM1lpNUZF
            WXdCY0tTdVhSNURqUUM1c0ZMYy9tWE0KBIBp/OvrJ+3svc7UvztMuh4ob0Yk+AE7
            jTVGCj3w4BQok4xgZfy2PPV3/WouhDYh/1mf6jpY98vTVW06Z2Xkxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jgsuq5wf3jv426rhst5saxc3etz29te3dx3tugg7466tje3layqvtar5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydFJJYndnNkhiamQvam1x
            U25OeXBHcW9XQTljeGhwTkQyN1pLbzl4em1zCjBmelFoS2ZERUxvd0NEY3ArVXEv
            bGJYYUVqRjllR1hUUjVwS1cyb3hIKzAKLS0tIFBDWXprNWI3U2JKUnljb0NnS3Q1
            bFN6cGR4UnBIaFF3MzhuSGREN1BuV00K80OJXEn2F6/myo4x3QJFu57RnRiJQfEJ
            YFOtjwlUGucqiGJqlIBfejI6fvCuSRWlCXbDSidoLg/txM+2rVfDaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x7t6fc2ccamga64a6lz7kxjv4txplng8272jnfx0le2vkcpyvuxq0jphnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNGNLMXM3aWlpdzZ2aDNS
            NFpsYUVHbUlzOGFvZFJHQ3JqK0g1OGhuckJRCi9GUVRFZTROK0tlTmV3dUtCclNW
            R2Fub05jczZ2UzZtbVNwNXZBeXJVc1UKLS0tIFYxNnpJaGVEZWNoZGxJdWhzNE9L
            U3lkKzFKUi9RSy9kR1dmT3ZTRGN4MlUKpg/txDrwbfZabmKTbJ46Ao0Ru4ncYv+2
            xU56ADnFoE2Sk8Bm/HpERE1GVQu52yybeQLOTbC/2UT+5VvVQKMY8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158unsxrql4w5huz4pjrr50gswj3tcnm3lxwd8ae54ye26pk454xsm5jwcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2JISUpEZGRHTGdTaFhk
            aHpiZGlZYmZ5dXBqazkxcGhzVkFISGNmMWlBCnpXQW1EOFQza3BrSHA0bjBkOWhI
            dVgrRVJ6c2FCM3Q3ZGx1QTlkZHIvMlEKLS0tIDBwVzJEcjZsZ25hMGQ5YVhqVkZS
            QXFLaVRrSWl0a0tORlR1Qjl4aUZmZ3MKjJ8fH+5QdT/i6bkBI+js8uSRUS6leGbp
            d4Mz1KzSzbeZ6+4Ka0m6ZQ8fnwa7pnQx1q5W3Y4GHQp3Riz9mNU/Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T11:59:09Z"
    mac: ENC[AES256_GCM,data:pAZtrbKpViVHfuDWMSy1xdJ/BZjXICiCb54EzVKrr4w9piOdx4tSKzIwfB0rtcbFzz7qLFqUEN3YhOuw2k7RRNjDjImRIOTzqz1Hnjz4UOeGSRyBJRgrnOdxm7+a5b6a8rcO21I7XQiSH+fegBu29DTMV8rxQhl7jBNVP1VsWK4=,iv:a5apDatLJUhIh4Nxwb6Jp4QWvtLtFQdIv2qupvoUVak=,tag:GjRqBiKg8l6BPm+y/AQSWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
