#ENC[AES256_GCM,data:bbiWlc9VcxXVsDOwjkl2aMJWNL/yd2DVJ0GvyrILFI8oYiCBr2ojmn9iO+w=,iv:PZ3Ot7G6GWMbPgchjVSIP9HfKv7RcFpI8ZnvIwvYXwU=,tag:Fk3YFxB6rymnZ1P426kY8Q==,type:comment]
#ENC[AES256_GCM,data:+gdsHvm3SWgoJS2ThaiHRvs50/+sq2R8JQ==,iv:C5yrYxR0yo2DhkzuTIYv/qU05g0l+pnqLHKleAcz0zk=,tag:CBo+TAed5S3SNYbKCwj9fg==,type:comment]
github-token: ENC[AES256_GCM,data:wdYXCm1ChcW39pP4PQDZdiccytOFxrw2k3oLUkkbUgM8wB89hr5K2BcWpmjIhH+7cm1pUjxJ9gLdftPpUvYEBESTiMnK++5exUw5X08GbBjwGfMGe9X6ZrwcX/Bx,iv:sv3VW99oiCIGNsbx/qi5oyD1si6ssQTHPLqd7IEOHK8=,tag:B1QMpNKj48TDQdVU1f+GTA==,type:str]
openai-api-key: ENC[AES256_GCM,data:l1itdOYYC81yDdkIeaP91vzTEearHW5GsFbMzmG56mD5Yv61WvdrUGo4/Z6cy611owTB8Xi2egHGOybLK15R8prd0ItvUNQB8eWXv/YFAweQ979Htv5cWdW3OvA/KiA=,iv:MvoIWB//uWphqNUsfqpPbKMwf9EO6KCtTa1ldU9/yCQ=,tag:NT29JTVOPusoC1IVEwwAfw==,type:str]
tailscale-auth-key-value: ENC[AES256_GCM,data:pNEWewIYS7jX80f0+ypFpi0FJfWaUWyJgBL/48zzRmY5vlGucpPMotH7XF6Zm/02tpP4T+kAMJ27hJLv6g==,iv:M0I1VuePyLTRjKM5GWpBzSjO2v+Px929dw0E1q2cBvU=,tag:FQDuffFvxGjekIeaR3PCWA==,type:str]
tailscale-auth-key:
    env_key: ENC[AES256_GCM,data://7m/N7RNluPQdSvURI2gkZU,iv:OzexAONw9gS+1exEI2iRKxWK/Ow1Q6RCxjojbRqu6SQ=,tag:NgnuhAZEOCVdhXgyAYRg7A==,type:str]
    value: ENC[AES256_GCM,data:8XCG/x2dL+j1f9L1bNTSq2dnxUazsWMHVaaQuULLuIEEWa4CT9QreEOWKXicuehy0StmPUuMDDN2FyqAtA==,iv:KbHaN9nDJ0uRfp7XHXyXuzpiq8oF5x+ueVMBIt2XmUQ=,tag:ksQAk3fErIm3i1Ldzj9n1A==,type:str]
    description: ENC[AES256_GCM,data:uPArnMqj1h/zqMdSTKE1D1Fo0g==,iv:Sb2gfrmTMpJ/AT3Fv4BgNwb5CKr4I7+0JuCvu8WI9S4=,tag:eXsqhhJtoecSHzcmFbc79Q==,type:str]
    id: ENC[AES256_GCM,data:r5mnshSB7S6qgH4JXV7vuG4=,iv:bj7L5dXRSXt50090D7Vd8CzYTLIh8aEgT8xpqjPIIww=,tag:zH72Ogo7jjJi2p+PUAq9xQ==,type:str]
    type: ENC[AES256_GCM,data:WJf0DDuYFaY=,iv:P6CaY4YYMR4k9ziX05YmGZMLfm+NzT1IC+x9n9aUYB4=,tag:TZWsh07evbmQkqc9LxY1vg==,type:str]
    expires: ENC[AES256_GCM,data:rkRqdkF6OC+oOQTOHIParJOOk9mj+7wp,iv:hW19cKHsfvqNQ4HdHrRzO4KCyjd2Fsv192XtNV+d3Hk=,tag:yxdkipVA5vQ0Uxyy9a4MBQ==,type:str]
    created: ENC[AES256_GCM,data:581i0nS6m2Klx1FVGWGJuH0kdUYYz2jQ,iv:ijt1NySwGkmOcqoayhJ+jEn8uvtNja4FreI/pcChGuU=,tag:9fuAFBfeqcprAZqaZrwH0g==,type:str]
cachix-auth-token-value: ENC[AES256_GCM,data:OrcmrZUKupt72Aiv+/JubTl87u/E9oh44vA2Vh+cczR6jmqy+AV42efJQtLtRS7FAze7TD/f+OyDJiElpoBEDiSLeeIvrXoBRRy5aDnsdw7Yo696KwBHFRvKiEZq1n+Uk4AV3um90wyiqQW8tPzSvJcLTy4s6zHp3URo6DSc567jZ5ZvK8ACG8zGgX9CxliBybkCh1s=,iv:0Cf1Otpq7eVigU+FxRFdTNqZFTFA/IbBq53zfqdVuWs=,tag:utOsBfL9NFZ1359RLDFADQ==,type:str]
cachix-auth-token:
    env_key: ENC[AES256_GCM,data:oRU+5Z/7tgJnyorPmWPZqoc=,iv:ffm7SJLIbRxKk+lD1QMMdGoBvibZwIIhd7PPbZcp8to=,tag:zKIodQ8Nw50+tTgg9M+LoA==,type:str]
    value: ENC[AES256_GCM,data:7MhQxO7RvmPCkZLPE+yi69f6RDI6B8Jd2jJEDxcDPWWIxDwCH1+Sy0bZcsdO9uW4I2bXj9NKxnv2aiIIYE5wHg7kqg2jbokoAu2rqWAUcVN7CFOKA+pukZT298EsIVeQxUPXMSiKefVgr92hop/cuqO76zMtiApI5Y+fCt7WW67rF3oOcACWXBdTp/xByr85iBJd7M4=,iv:QP8U9Edc0Rv2QeYpORGxElXcrgRQ9GSuSQzQdVeJN8o=,tag:p05Q3ws2a9mbmXvZr7APgQ==,type:str]
    description: ENC[AES256_GCM,data:SBxAjaX8ARYiOIiU6ZiAEw0dEq1Shw==,iv:blzrBuuTmQtQRYeHxLKjmibzvw95rUmI4IAY5oRJJNc=,tag:RJUBly35ooR+ilPrVbH7Nw==,type:str]
    permission:
        read: ENC[AES256_GCM,data:qddNaQ==,iv:JhI66D6ZeAhfRcWjuDdqbt5e6XlMmyQt/+2/hkzydgE=,tag:viQUuGGPL4Pjp7P2zxFcxQ==,type:bool]
        write: ENC[AES256_GCM,data:XbmfVg==,iv:N5Lo4cRrbtWJIy789PRQV2jt9UfLl2OZDKBn8Wv3jl4=,tag:YcH04Bqx4iPDrXQsAAYfbA==,type:bool]
    created: ENC[AES256_GCM,data:KmIHFhk9LK/yfirSnP/i+XjV8hbKbAmJ,iv:Jr1AT/lW5dvaRRSxnINcOl8jJq1EoJrBOZqpPr1mlpg=,tag:Ozrx4Is0fhVc10fxKtMS+g==,type:str]
    expires: ENC[AES256_GCM,data:nd8rYM9NO3GbNd6OzYDSNCFBSky+bW+1,iv:xy9HNcT07B5juQu+9q7mbBgajDvRyteB7HlTFxBE2Qo=,tag:b96L+XMrEk6JjbkKx1Yzlw==,type:str]
    action: ENC[AES256_GCM,data:vwMzA7B79MYrra9iI28ADi+hO7ql,iv:oGv+nLqHaJBxoWWfU4rrf7ZGh9nK/8Z/zTASS9f4T4o=,tag:aV7hq5yGnJMoChyieMN0zQ==,type:str]
smb-secrets: ENC[AES256_GCM,data:M7xe8CzbIihjULi9NpCqPo+ZerS+6SxCHrPn1VGOcMPxLW5TfR8w+4rGI5r0LEinaKxu1waoGlvu,iv:b3eMuRvYgLGkjRf5PjEkXXDxSIwWHGLldW69t8tL9HQ=,tag:B1OIw0+Y292wyCavB+AxUA==,type:str]
wireless_secrets: ENC[AES256_GCM,data:eLR1yLhJRo/l1ZOL7lQgAKfvNDSKoOmaD7bgwlZ4X8bALp2zOdXIp0SmRDsY6FK/K6iHVYRlNyGwbLdbW6fL21cO3SHbXEkqsxylP7nZLMw=,iv:W3jMiL4hd55Emf+0I1lsAHb6nxZKDaeptnSCZyUT9XA=,tag:0DBDptG/WsniRxNf1jtGIA==,type:str]
wpa_supplicant_conf: ENC[AES256_GCM,data:JXP1n30BLFNF6IskfiptMMccoNyFgOQj+fM7jJfmrI+fGnzQJRGUB9rgezN2QVdtUMcQOltKjK5VO+Kv5dSGmQrjGv4tiHv9WEZjoNK9IfWRVk2RAwwMZYcSXGDqPBFxk8KqshxlohMfuzkMRfqLFbAUeL+4RkCaQXrdMBhLC8VR3HjAEhqizWcGhcTLXI4VHoBFu3UHNjetpvCFd4PeUXBQsqlEOgLSOoKL+VjkuLBlcIea002syw1UqVN6576jnb+i5givFc/MYCLFrVD7SzR+LxOL1d0YtigyM+362BNzKgjUyrOtaGZ4Wm8PkAqyoaQD2ItrUYMP1KF9o3f+azP9RnULCN0cGvZQWf8ppmYcvy1aVH2mcztCyo0DBDxFHhng0sUe8DDojZ84pacg4Lt319eOLOWfj5/JZXlZI1TFvU9npLMF2kYwQHPTLZu41PBTTuv0WP9tW9B+gxvDBRehIYrIPpQ08jVFtb2MXZD6N7Cy+C4T5SCOPfLRIm6eSHrqGfR+t4zC7M1erSiyadV9v6wxel8Euv7x+JLPKyxmn7E=,iv:QSz/HPRrtwmwI9SNqAVudnTWLSuQMVFKE/iro1P/b8c=,tag:MoBWnMx7RPSn6Mi39AWeYw==,type:str]
redshift:
    latitude: ENC[AES256_GCM,data:9XgxjV/QFzM=,iv:aS0HcCJ2hLXh9nLkKe1ZcJeYwZ0UxmqZ4ftTZ2lnQNo=,tag:z+skAQ9Mpshp7Fr6nu7N1g==,type:float]
    longitude: ENC[AES256_GCM,data:cU9UP2/Yeg==,iv:yR58yiWyeyCrrouV7OruclDEFQvGTcfC34TOyMlh948=,tag:Q9WSXepjUWcSg1JU8y+bGw==,type:float]
users:
    geoffrey:
        password: ENC[AES256_GCM,data:gwkr7yycImwVDZeTeKq2CfXGE8P6sgfGv1Tnlow7Y41mv2heERR59ouBsIwNVaTUg+zfERRMniP0aSLfmk2RuQH8z1B0uPebXQ2y/wlmHedBWW+BTu93F+gVYgOru/d0OyejIeJfpUdL7w==,iv:IxXrIMxlglNpAdmmt0Z00zNqTt7xrg/hv2uRxhkU87U=,tag:qdo9KAqpROiBCsIXMI2Tpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kdp9ndxywv48mapkkejujvzfqhxzyzp6s7kp42u7ynu6q5e8sqkqp0w7sv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSzN6QjVoV0djeGE4T0c0
            VlNWRXVVOVZ6dnNQRldBV0dGTG1sTXRkK0FRCm1BM0JUS09ITFpCNzN0ZlF0Z1lG
            amJ1NHRWYllpRUJ6a3kzdE5tWmxRQ2MKLS0tIHJsK3JRNHlPajhPVVljL0I5ZVMx
            RVdqcUtTNFZEWUZheFd4blZPbGNmMGMKBqELsVOF+gMbvBUXRoMx8FdWQeTFb+G2
            TUMUa97odMY4VjJvYSN49u1DBLwTQYdJhnwz4OODx+z6sJaCuBojDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tpj92c7aqe8df7g3qf58vzcyevx53vhap3qkrxa9calpdtp5vvmqrd0de7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMTk4SXQ2MlAxM25hRzB3
            SCthQnQ0NjVTZWNIYmJQNzlUaTRBcUFQUjBnCi9TOEJGYTk2NDdEZHg0OXFzejhR
            RXBuS0crRjhkeFhkRUZsdlJRZU5vZ2cKLS0tIDN4ai9wbEF5SXEyekRIcGp4Qlgv
            V1lESmdwNU8wMkpSenRzVXc4WmNuMlUK7KwnZ9QOdC1lAxjxYxdD3GE/WbCmj6Ef
            9BXHDqsbkBFljp5HKVKsZpXQi/FW0K7fD+4oMREZenOB11oImr1pKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13sx384sda6z7lvg6arys4asl4j88t652y0r9km86n3xrsuh5hpzqndl9lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS2NVekkwZzBGRFVQRHIw
            MEJtY29vem9TeThpU3BEcXpkeXF3VGV6ZWk4Ckk5VXZoNWFvMC9MN0V1RDdPcXZ6
            b1EzYm9sQ1VZc3l4elh0a3I1c2x1cmcKLS0tIDJQTUJiU0gxcGVMTEFTZ3NXSWFK
            MUhEVENZaWdBc2dhOUc5dEUvRk9wSXMK2WOZjZDToLTxMOBzG6ujPrFTyUZe12+5
            d8UcIRmONk+tV2MJUAvigOMEgTWjkVEGC9BLCdbT3IsRWAeHJX+CXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10nd9h4mh8vuq7h29karutjw6227g26uuztuut82p08sdc2vel4gqr4c62e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQnF4eFpxakJNVG85V0NM
            UzF5Rk55RTRneWMyQWR1ZWYyRzJVY0ZCRjBFCnIyTDFBd0doQ0lFQ2l4M3BOYnE5
            aUlaTkRMeU8zcFNzZTJZMXZnR0pEdTAKLS0tIGRCNFdSMlJSNXZiV21YYXFFbkZM
            bVVLNmltQmE4MGxEQWdQWS9IUTlCdGcK36VWN0WQw9B7SUvXa3uOpR7LI1FmZHFy
            ba8LKXmK8+rsZK7C/OO//FLgO3Gn081lU04vD4Nf56K6Jtfqf/+BKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rw2gs2s2qfvvqt7c2nls758xvta4qxphy980jz7apt3vrl0gxdvqxfplrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cklVakRQaXF5WXNkL2x3
            aG1vNW5VbTVTaHRDQ1FqdzA2VXNRNHE4dUR3ClhJSmFRK0phblcvckp5NDlxZTBM
            UGI4NGV3S0wxb3RrQllUejc2VTdaWmMKLS0tIEJnQ3M3WVd0NUpwYWVyK3hRanZY
            N2ZmWGZudmJ3VGdzbzdTSEVuRlliUTQKfhfK403JwA5x8TKa+C0FC/3haXulQWbv
            XZtcEnwjLEd9yqZNNktOIW+4760UukRTZcM1TX73cLG8UonRzfNbSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a9lryzapql62vy05w9twp3kx98e4yrr8re5lu8hpgca3ccl2ns7q4yqz7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWmhqa3h5R0lQREcyWDNp
            VVVrSUd6Qms5N0JObWw5RGVkdUhoanlzSzI4CnVud2Q0ejZJeUFNWGRmRE85NllB
            Zmc5VXovaGExeXlzSGxIbHRuNER0ZmcKLS0tIDBKSmJTL1RwanVUK3VkclRqUEFN
            UFZQdFdvbDRrZ2lWeERZVVdNVitPWlUKic9mE+Z7Vk2Pq+2n+xWebz+eCXNqZRHT
            7dbzaALjUxsj/q6mL/WeybkzznEX5BQldEvNx6AxoVvZkj817/AwcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qhdnzdutndxnmd074p736qwznwp8683zhs6nrn7qs8ucmnel2qpsrase8c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWnBDWVNvbmxZeVFUZHB1
            b0oxKzdPUjZ2SDRNSGFzczhpeTR4eThhd3lZClMra3JsQmNxeTBEU1BWSUlERkox
            UllKL2VrTE9La3o4MzVudzRhdFZaZmMKLS0tIDRBT1FBeVRoSEJSRjlGWk1FNGll
            dEpYT29WbEtER3IxUDYvVWNzVEdtVTgKm3VgxHPv/knVFa26EcarLrh9NJWFgFvI
            obcucyI3u7oCS2oek1zx8bQdLdmR2nMDA+sG34yQkouFxruSt9JFEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14hqjh7pas08vlyuyppdfuc03yn94mpt4ld6zw293gkvnceduzfcsvmd2lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNVV4RTZucUFRUnpJZkdp
            Y0l4SENZK2YwUlQzRE1KVGxWSWU3ZDhYempFCllMWFM4ZWZFQVVtQVd0cUhNRGNa
            NHpVbmhZQS9SR1JLbXd3SE04MDNPNEUKLS0tIEVoK3dEM2dTL3VyR1hQaVBOMEM1
            T05RaUczUCtNOTlDanhONG5OdlB4dm8KuH6KnMcx8pOrnh+ZOj4QEts4gv4NRne4
            mSzPPmN44Dk2/LW8k5fOmRukAGnCPk6n8pscG3ixzhOMLEMGlf2Gqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjc5zrcvex4r8tusuvwv00tk6srnerayle07unphz7kq2jlzm39qc52wdz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM3N5Zmw2Q0VLaU9KdkNt
            RjUyWmpGU0RUbzVyZTRuL2NhQndQMjdmT1ZJClEvSzJ1WUtBZS80Zm0wclBjUHA5
            VVdtQWp3NCtVZXA3QTU2QTVybHJsZHcKLS0tIFQ3NGdJdmhoc01qcXNGcml1ek85
            V3YwakRIOWdDVTVwR0xvLzhFZXdGVTQKpMmLbeEeBQfEvTr9z6FTi1lNSgHrwe13
            8x2t0OiNfmEObwxNPsIcvjIS+VmMQqpDHgf5Ui+nS7vYCl/+UetQ2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z09vrs2ketcn244l43fjxgzuu22yp0q0tpkmh3s2grlqn8jgypeqgnnf9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjM1R3cENNV2pBWkxYbmM3
            VDMvb1VFZnpTSnVPZ0dZRjd3ZFNLVVUxa1RBCkQzMmQyaXlZb3k3TDBoSGs2Vzg5
            VGx3Y3NRNDBWQllsTXhPdjJ5dVJKNTgKLS0tICtxcVd1UFNCbGpGdjRwZ3U0ajIz
            Z2ZPRTZUT3FMWStlZk9pbmtlanBuL00K7/GV/GHCuvIhMklJXJt4UYr6k8Np+Y0A
            3LFyCTMl5HRsVa7vUFQjRaC76GKuNo+wIQ84GnR06hLspf9KV9MrLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T19:43:55Z"
    mac: ENC[AES256_GCM,data:0NogcDdqc9jH48VWZZ0E2kiMm6eq2mokVrObB+35fcg2N0Bz0TMtkC/iqsKaukhEN+kJMiIZJwdhrUIEaW+jouVzznMjoRUNSh/cJaBLBqpWOzeQ3MQ94TDJF8SKAL6h0iJsNN1E4HnMANTrxyNDyM1lpk75yQyv/rK1KVMnmeA=,iv:TF1KUxaGTAufrnyVoWDHmAe5wUjU3gRaCGxCm0k/FdA=,tag:fBaS0deaiAKpWs/0mnMY2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
