#ENC[AES256_GCM,data:bbiWlc9VcxXVsDOwjkl2aMJWNL/yd2DVJ0GvyrILFI8oYiCBr2ojmn9iO+w=,iv:PZ3Ot7G6GWMbPgchjVSIP9HfKv7RcFpI8ZnvIwvYXwU=,tag:Fk3YFxB6rymnZ1P426kY8Q==,type:comment]
#ENC[AES256_GCM,data:+gdsHvm3SWgoJS2ThaiHRvs50/+sq2R8JQ==,iv:C5yrYxR0yo2DhkzuTIYv/qU05g0l+pnqLHKleAcz0zk=,tag:CBo+TAed5S3SNYbKCwj9fg==,type:comment]
github-token: ENC[AES256_GCM,data:wdYXCm1ChcW39pP4PQDZdiccytOFxrw2k3oLUkkbUgM8wB89hr5K2BcWpmjIhH+7cm1pUjxJ9gLdftPpUvYEBESTiMnK++5exUw5X08GbBjwGfMGe9X6ZrwcX/Bx,iv:sv3VW99oiCIGNsbx/qi5oyD1si6ssQTHPLqd7IEOHK8=,tag:B1QMpNKj48TDQdVU1f+GTA==,type:str]
openai-api-key: ENC[AES256_GCM,data:l1itdOYYC81yDdkIeaP91vzTEearHW5GsFbMzmG56mD5Yv61WvdrUGo4/Z6cy611owTB8Xi2egHGOybLK15R8prd0ItvUNQB8eWXv/YFAweQ979Htv5cWdW3OvA/KiA=,iv:MvoIWB//uWphqNUsfqpPbKMwf9EO6KCtTa1ldU9/yCQ=,tag:NT29JTVOPusoC1IVEwwAfw==,type:str]
tailscale-auth-key-value: ENC[AES256_GCM,data:pNEWewIYS7jX80f0+ypFpi0FJfWaUWyJgBL/48zzRmY5vlGucpPMotH7XF6Zm/02tpP4T+kAMJ27hJLv6g==,iv:M0I1VuePyLTRjKM5GWpBzSjO2v+Px929dw0E1q2cBvU=,tag:FQDuffFvxGjekIeaR3PCWA==,type:str]
tailscale-auth-key:
    env_key: ENC[AES256_GCM,data://7m/N7RNluPQdSvURI2gkZU,iv:OzexAONw9gS+1exEI2iRKxWK/Ow1Q6RCxjojbRqu6SQ=,tag:NgnuhAZEOCVdhXgyAYRg7A==,type:str]
    value: ENC[AES256_GCM,data:8XCG/x2dL+j1f9L1bNTSq2dnxUazsWMHVaaQuULLuIEEWa4CT9QreEOWKXicuehy0StmPUuMDDN2FyqAtA==,iv:KbHaN9nDJ0uRfp7XHXyXuzpiq8oF5x+ueVMBIt2XmUQ=,tag:ksQAk3fErIm3i1Ldzj9n1A==,type:str]
    description: ENC[AES256_GCM,data:uPArnMqj1h/zqMdSTKE1D1Fo0g==,iv:Sb2gfrmTMpJ/AT3Fv4BgNwb5CKr4I7+0JuCvu8WI9S4=,tag:eXsqhhJtoecSHzcmFbc79Q==,type:str]
    id: ENC[AES256_GCM,data:r5mnshSB7S6qgH4JXV7vuG4=,iv:bj7L5dXRSXt50090D7Vd8CzYTLIh8aEgT8xpqjPIIww=,tag:zH72Ogo7jjJi2p+PUAq9xQ==,type:str]
    type: ENC[AES256_GCM,data:WJf0DDuYFaY=,iv:P6CaY4YYMR4k9ziX05YmGZMLfm+NzT1IC+x9n9aUYB4=,tag:TZWsh07evbmQkqc9LxY1vg==,type:str]
    expires: ENC[AES256_GCM,data:rkRqdkF6OC+oOQTOHIParJOOk9mj+7wp,iv:hW19cKHsfvqNQ4HdHrRzO4KCyjd2Fsv192XtNV+d3Hk=,tag:yxdkipVA5vQ0Uxyy9a4MBQ==,type:str]
    created: ENC[AES256_GCM,data:581i0nS6m2Klx1FVGWGJuH0kdUYYz2jQ,iv:ijt1NySwGkmOcqoayhJ+jEn8uvtNja4FreI/pcChGuU=,tag:9fuAFBfeqcprAZqaZrwH0g==,type:str]
cachix-auth-token-value: ENC[AES256_GCM,data:OrcmrZUKupt72Aiv+/JubTl87u/E9oh44vA2Vh+cczR6jmqy+AV42efJQtLtRS7FAze7TD/f+OyDJiElpoBEDiSLeeIvrXoBRRy5aDnsdw7Yo696KwBHFRvKiEZq1n+Uk4AV3um90wyiqQW8tPzSvJcLTy4s6zHp3URo6DSc567jZ5ZvK8ACG8zGgX9CxliBybkCh1s=,iv:0Cf1Otpq7eVigU+FxRFdTNqZFTFA/IbBq53zfqdVuWs=,tag:utOsBfL9NFZ1359RLDFADQ==,type:str]
cachix-auth-token:
    env_key: ENC[AES256_GCM,data:oRU+5Z/7tgJnyorPmWPZqoc=,iv:ffm7SJLIbRxKk+lD1QMMdGoBvibZwIIhd7PPbZcp8to=,tag:zKIodQ8Nw50+tTgg9M+LoA==,type:str]
    value: ENC[AES256_GCM,data:7MhQxO7RvmPCkZLPE+yi69f6RDI6B8Jd2jJEDxcDPWWIxDwCH1+Sy0bZcsdO9uW4I2bXj9NKxnv2aiIIYE5wHg7kqg2jbokoAu2rqWAUcVN7CFOKA+pukZT298EsIVeQxUPXMSiKefVgr92hop/cuqO76zMtiApI5Y+fCt7WW67rF3oOcACWXBdTp/xByr85iBJd7M4=,iv:QP8U9Edc0Rv2QeYpORGxElXcrgRQ9GSuSQzQdVeJN8o=,tag:p05Q3ws2a9mbmXvZr7APgQ==,type:str]
    description: ENC[AES256_GCM,data:SBxAjaX8ARYiOIiU6ZiAEw0dEq1Shw==,iv:blzrBuuTmQtQRYeHxLKjmibzvw95rUmI4IAY5oRJJNc=,tag:RJUBly35ooR+ilPrVbH7Nw==,type:str]
    permission:
        read: ENC[AES256_GCM,data:qddNaQ==,iv:JhI66D6ZeAhfRcWjuDdqbt5e6XlMmyQt/+2/hkzydgE=,tag:viQUuGGPL4Pjp7P2zxFcxQ==,type:bool]
        write: ENC[AES256_GCM,data:XbmfVg==,iv:N5Lo4cRrbtWJIy789PRQV2jt9UfLl2OZDKBn8Wv3jl4=,tag:YcH04Bqx4iPDrXQsAAYfbA==,type:bool]
    created: ENC[AES256_GCM,data:KmIHFhk9LK/yfirSnP/i+XjV8hbKbAmJ,iv:Jr1AT/lW5dvaRRSxnINcOl8jJq1EoJrBOZqpPr1mlpg=,tag:Ozrx4Is0fhVc10fxKtMS+g==,type:str]
    expires: ENC[AES256_GCM,data:nd8rYM9NO3GbNd6OzYDSNCFBSky+bW+1,iv:xy9HNcT07B5juQu+9q7mbBgajDvRyteB7HlTFxBE2Qo=,tag:b96L+XMrEk6JjbkKx1Yzlw==,type:str]
    action: ENC[AES256_GCM,data:vwMzA7B79MYrra9iI28ADi+hO7ql,iv:oGv+nLqHaJBxoWWfU4rrf7ZGh9nK/8Z/zTASS9f4T4o=,tag:aV7hq5yGnJMoChyieMN0zQ==,type:str]
smb-secrets: ENC[AES256_GCM,data:M7xe8CzbIihjULi9NpCqPo+ZerS+6SxCHrPn1VGOcMPxLW5TfR8w+4rGI5r0LEinaKxu1waoGlvu,iv:b3eMuRvYgLGkjRf5PjEkXXDxSIwWHGLldW69t8tL9HQ=,tag:B1OIw0+Y292wyCavB+AxUA==,type:str]
wireless_secrets: ENC[AES256_GCM,data:eLR1yLhJRo/l1ZOL7lQgAKfvNDSKoOmaD7bgwlZ4X8bALp2zOdXIp0SmRDsY6FK/K6iHVYRlNyGwbLdbW6fL21cO3SHbXEkqsxylP7nZLMw=,iv:W3jMiL4hd55Emf+0I1lsAHb6nxZKDaeptnSCZyUT9XA=,tag:0DBDptG/WsniRxNf1jtGIA==,type:str]
wpa_supplicant_conf: ENC[AES256_GCM,data:JXP1n30BLFNF6IskfiptMMccoNyFgOQj+fM7jJfmrI+fGnzQJRGUB9rgezN2QVdtUMcQOltKjK5VO+Kv5dSGmQrjGv4tiHv9WEZjoNK9IfWRVk2RAwwMZYcSXGDqPBFxk8KqshxlohMfuzkMRfqLFbAUeL+4RkCaQXrdMBhLC8VR3HjAEhqizWcGhcTLXI4VHoBFu3UHNjetpvCFd4PeUXBQsqlEOgLSOoKL+VjkuLBlcIea002syw1UqVN6576jnb+i5givFc/MYCLFrVD7SzR+LxOL1d0YtigyM+362BNzKgjUyrOtaGZ4Wm8PkAqyoaQD2ItrUYMP1KF9o3f+azP9RnULCN0cGvZQWf8ppmYcvy1aVH2mcztCyo0DBDxFHhng0sUe8DDojZ84pacg4Lt319eOLOWfj5/JZXlZI1TFvU9npLMF2kYwQHPTLZu41PBTTuv0WP9tW9B+gxvDBRehIYrIPpQ08jVFtb2MXZD6N7Cy+C4T5SCOPfLRIm6eSHrqGfR+t4zC7M1erSiyadV9v6wxel8Euv7x+JLPKyxmn7E=,iv:QSz/HPRrtwmwI9SNqAVudnTWLSuQMVFKE/iro1P/b8c=,tag:MoBWnMx7RPSn6Mi39AWeYw==,type:str]
redshift:
    latitude: ENC[AES256_GCM,data:9XgxjV/QFzM=,iv:aS0HcCJ2hLXh9nLkKe1ZcJeYwZ0UxmqZ4ftTZ2lnQNo=,tag:z+skAQ9Mpshp7Fr6nu7N1g==,type:float]
    longitude: ENC[AES256_GCM,data:cU9UP2/Yeg==,iv:yR58yiWyeyCrrouV7OruclDEFQvGTcfC34TOyMlh948=,tag:Q9WSXepjUWcSg1JU8y+bGw==,type:float]
k3s-token: ENC[AES256_GCM,data:jts0Eu2nOk5+Xyny3QXLNrtMACipfBUPs5R/Eb8KinjwHHDq2W58Ld/b1JpFrG2IBPsR96pS4TSYcTLwXRJGhKUGpvPldlSZOkplB7v18CsyHvHDXJJnksk/GdGXPrWUPC5Sal5uEj1onlCM,iv:QCp9USw5Dz5ENqE0qBPGqPhkHAFbMwQV0J7+yfYRT6s=,tag:5KKSAdHZF86mgYRZFm7Nog==,type:str]
users:
    geoffrey:
        password: ENC[AES256_GCM,data:PGt7YUcqqJsUJgCA7G0F7qI58E4qt4QfGMijjE2cqQNOVE1gY5B9juA7TIX0o54twagPfh6FwJGt2/E6C4mSi0NR0yPctUlp4A==,iv:J6PZStrY8m9shi9rL5aS4MNYwhi2pEzDwfVyWF0rtT0=,tag:YiD2Ife5IaNY1dtS/NlgPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age173mhqrnhztgrrjc5vykz4hxmku7kplsherscym3ummxyg9dtf5vqqq72u2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYXQ0aEhlNUJlN004VkFO
            a3pDelRTUlJpQXFsbGNaSjFENkdBZ1NVdFNZCnNTOG5ZYU0vZHJJaGZRYjRMak5l
            Rks3RmVFY0FKMU0yQ3JJWFdBN29jT0EKLS0tIFRLRnRsQ05EK0pBUjBXa2VUc0py
            aHl0WGs3UXd6MmRHcGRBYm45bng5MzQKTTo9ADQ3yeHksubY4p2l/rN2oqaXDUa3
            ZwBLJ+Rv59i2BTJN2or9HQYKrJeL6QmofiCCCoYOKtUg0iq1eAg1Nw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdp9ndxywv48mapkkejujvzfqhxzyzp6s7kp42u7ynu6q5e8sqkqp0w7sv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUzgwT2Qrcm1PNjdsOWpO
            Q0E5UTlMUy9rc09GQnY2a1J5TS9waVFIcGtBCkUrM1ZkaFV5eEJLMW02TTRBaGxG
            LzhDT1prbXJNQWRvZThZZDRYQ1E5OVkKLS0tIFlycG5PS0lMZmRoVVlnSXo1bEtS
            OGNNd2lwOXRyNVEzSkVWRlZPV2RRamMK9Rqxk9+gJR/+HVJiu1j1ZXzhq8QuPMUl
            uZDOABPUrIP2cZP9UF4SA8GcmB/zXDRhwbdigMrw0vFfQZqcLYuK8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tpj92c7aqe8df7g3qf58vzcyevx53vhap3qkrxa9calpdtp5vvmqrd0de7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WXZNcEtabzd6aTBPR2U1
            WlBMcDc0NjF2T2ZtR3BGTmVFTEpkWlVZcVdRCkc2c0dZZmR6S1BoM1lUYjZHQWdq
            c3g3dnZ1d25aNjF3QWVCL0VodWFzeGsKLS0tIEhjdzZKdXZHck8yMGZPbXE2Yk85
            WWxaTUFDV1VUeVR2VWpISTBEcjIxV0EK3rQbzGBo5XimwyLGYJCXNU5wOG1+ZDfx
            24WlyA0ncI+B+X+pSADEpDUrBgm2wDv1QlBhMPDzpGsq+drFBTyWTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13sx384sda6z7lvg6arys4asl4j88t652y0r9km86n3xrsuh5hpzqndl9lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQ0VOVzllQmRzbUtkZ0pU
            QW1zOFJLc0pwVEhDQlYzbVR5NHFrYVI0UDA4ClBRL3NVVkc1QWZjVlBPald0RDhl
            NXJMWWRmMU9GVWxQZm44Ti9BdElOOFUKLS0tIHB0eitRK1hRNlZWK2srWXlFS0JO
            cE5zK00yM1U3WllyMlpLNk9pOHBxdWMKr/mkcbaFKkAO5Z3c4nTCvQtsGZi9lYCB
            UWrDWLCqWKKUvBcCrJE1nmeh+TuOCVOzi83ULq6bfscvyJ2lsBtrTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ahyztttw0jky84tzg5vzvhwvhy3c4ptw7zg4kv5jrn4ergjq2c3q4f76dv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlNCZk9NRTFjNHI5bmtL
            MHNQUklteU9rRDU2UjgvUDNNSzRxRkV5YzA4Cnd4OUFkSi9XL1lmQ3ZrNUI4Qmx3
            amhEck8wTEdZTHFuZVN2ZnJMbXhUY1EKLS0tIG1YZkMwdEVQanc4VlFPbTRHTk8r
            TGpRY003WjUvNmRtYUlIdkY1b1g5OTAKah9BBQA+BHEr5CE62aljIU9q5tAPGR7L
            LwfvXtp59kYlUDD+sX68tcHgvgAsSVsx7J4aOphwaBucJ1BFvw6+yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z09vrs2ketcn244l43fjxgzuu22yp0q0tpkmh3s2grlqn8jgypeqgnnf9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV0Rla1NJSmMzMzlpWFEw
            ejFtZ2pYNk1qNjRFT2ZSaTg5MWcyeTVvTEZVCmVMZk5vK05MblcrZS9XVWc1QkJR
            MTJReHBlTFg3Z2NPK0Voa2lwRW00NnMKLS0tIEVuM2Z5TmNTS3hRRFZ5eFcybndC
            ekhocXAwbkdUQU03bmZ5dlRGdXJudmMKe0Ac1R+vpfLZ3Ksfq0tDPEKdqneOBUcz
            HJjAHNl0WIZZNJBWgsgsd8h1n6HJGELuxCB+tOoE/6n/ZdpEBG5hHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jgsuq5wf3jv426rhst5saxc3etz29te3dx3tugg7466tje3layqvtar5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY3BRTW5LVDEwVG5lVGh4
            R1BvL0gwZlFMcDFWWVExOEQ2QVY4QzJNMUd3CkZqM25oSEtWaE9FZjVXU2c4TTh4
            bUxlNDRiOXFueWU2L2lWZTRXc3J5SlkKLS0tIGtuOEZ1SkdaNzR0MVVVcTN6NkZX
            YkxJbG9iZWJpaXZmS1FpWE9lN2lrUzAKSd6wlxa7Msh2yCNBSZXuhZIJCeC7BbK+
            /lFiWwTzFTq74qbptSDctlPIJpOCwX08veWVAprYCcWJYSdYXFCvgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mz6264gtrt32xj0hkzg620utf2eagx9p2k6yq63pxn4xnsv8jp8qn429m5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbmNjc0RvMkpLYTQ3UmFw
            VWVEMGV3Zk4xSXNJbkJlMDlCYnp3NkkzNFdJCkliZWZ1a1RPVERJa21ZZ3VyYkxC
            Q2dzSDN6RS9SU3RUK3JKZ0hmeXBjUW8KLS0tIGRER3dLUVNlRUN0WGgyYXF1dG9y
            S0lZV0NabjA3NXZvaGRDRmpReVRaMDAKjp8TtOjxZWiG3HzJr354RD/f8OeuQ53A
            pUV5qYRnMy1+SCmpHFOLq86V6tK5RxaT+mG/raV3i2mzXy/fGlzkMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158unsxrql4w5huz4pjrr50gswj3tcnm3lxwd8ae54ye26pk454xsm5jwcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbnErQjJmZnNZbkNXZ2Vz
            QTRxa2FsQjg5dmE4NmlPWkxXUDlhS1FyZVNBCkRoQy9kKytCUFpHaFh1dFExelNL
            YXB0S2ZhOHhKM0JCSHZnVkZIbXY3Yk0KLS0tIDlqS29sZC9PaXd1dDhVRGtTV2N3
            S2N1dDQxcStVaDFtcEZQSFpwNm4wS28KEc8UyaQNN6U4kEQC+O6JbaOqpYde2GGr
            HoW5czVQMcIPz62FmH/h15ndpbdBSdmskhHftJW7uvtUfs1arueNog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T12:14:56Z"
    mac: ENC[AES256_GCM,data:YO4QvL1sEJ7PrGhDdhKLXSGVTCp8Z+J9WdCuvNO2OUBLGIIh4kGJRku7OvB7hbcaiTiP1iPWVDZf1RSsn/8rwCZRbc+tsZejmrUt4g7qvfE3arkQ6IINgRgH14qY9XhFs0i5Ajo3qnvDumtUi/qrMxs8v+ZqDPDgfMmCqNs3j70=,iv:nHnnkDzeOyVYr//qiqoO1fQ+99NvASD7spARe+FOU0M=,tag:2kk0dildmjN/22Wt/97MZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
