#ENC[AES256_GCM,data:bbiWlc9VcxXVsDOwjkl2aMJWNL/yd2DVJ0GvyrILFI8oYiCBr2ojmn9iO+w=,iv:PZ3Ot7G6GWMbPgchjVSIP9HfKv7RcFpI8ZnvIwvYXwU=,tag:Fk3YFxB6rymnZ1P426kY8Q==,type:comment]
#ENC[AES256_GCM,data:+gdsHvm3SWgoJS2ThaiHRvs50/+sq2R8JQ==,iv:C5yrYxR0yo2DhkzuTIYv/qU05g0l+pnqLHKleAcz0zk=,tag:CBo+TAed5S3SNYbKCwj9fg==,type:comment]
github-token: ENC[AES256_GCM,data:wdYXCm1ChcW39pP4PQDZdiccytOFxrw2k3oLUkkbUgM8wB89hr5K2BcWpmjIhH+7cm1pUjxJ9gLdftPpUvYEBESTiMnK++5exUw5X08GbBjwGfMGe9X6ZrwcX/Bx,iv:sv3VW99oiCIGNsbx/qi5oyD1si6ssQTHPLqd7IEOHK8=,tag:B1QMpNKj48TDQdVU1f+GTA==,type:str]
openai-api-key: ENC[AES256_GCM,data:l1itdOYYC81yDdkIeaP91vzTEearHW5GsFbMzmG56mD5Yv61WvdrUGo4/Z6cy611owTB8Xi2egHGOybLK15R8prd0ItvUNQB8eWXv/YFAweQ979Htv5cWdW3OvA/KiA=,iv:MvoIWB//uWphqNUsfqpPbKMwf9EO6KCtTa1ldU9/yCQ=,tag:NT29JTVOPusoC1IVEwwAfw==,type:str]
tailscale-auth-key-value: ENC[AES256_GCM,data:pNEWewIYS7jX80f0+ypFpi0FJfWaUWyJgBL/48zzRmY5vlGucpPMotH7XF6Zm/02tpP4T+kAMJ27hJLv6g==,iv:M0I1VuePyLTRjKM5GWpBzSjO2v+Px929dw0E1q2cBvU=,tag:FQDuffFvxGjekIeaR3PCWA==,type:str]
tailscale-auth-key:
    env_key: ENC[AES256_GCM,data://7m/N7RNluPQdSvURI2gkZU,iv:OzexAONw9gS+1exEI2iRKxWK/Ow1Q6RCxjojbRqu6SQ=,tag:NgnuhAZEOCVdhXgyAYRg7A==,type:str]
    value: ENC[AES256_GCM,data:8XCG/x2dL+j1f9L1bNTSq2dnxUazsWMHVaaQuULLuIEEWa4CT9QreEOWKXicuehy0StmPUuMDDN2FyqAtA==,iv:KbHaN9nDJ0uRfp7XHXyXuzpiq8oF5x+ueVMBIt2XmUQ=,tag:ksQAk3fErIm3i1Ldzj9n1A==,type:str]
    description: ENC[AES256_GCM,data:uPArnMqj1h/zqMdSTKE1D1Fo0g==,iv:Sb2gfrmTMpJ/AT3Fv4BgNwb5CKr4I7+0JuCvu8WI9S4=,tag:eXsqhhJtoecSHzcmFbc79Q==,type:str]
    id: ENC[AES256_GCM,data:r5mnshSB7S6qgH4JXV7vuG4=,iv:bj7L5dXRSXt50090D7Vd8CzYTLIh8aEgT8xpqjPIIww=,tag:zH72Ogo7jjJi2p+PUAq9xQ==,type:str]
    type: ENC[AES256_GCM,data:WJf0DDuYFaY=,iv:P6CaY4YYMR4k9ziX05YmGZMLfm+NzT1IC+x9n9aUYB4=,tag:TZWsh07evbmQkqc9LxY1vg==,type:str]
    expires: ENC[AES256_GCM,data:rkRqdkF6OC+oOQTOHIParJOOk9mj+7wp,iv:hW19cKHsfvqNQ4HdHrRzO4KCyjd2Fsv192XtNV+d3Hk=,tag:yxdkipVA5vQ0Uxyy9a4MBQ==,type:str]
    created: ENC[AES256_GCM,data:581i0nS6m2Klx1FVGWGJuH0kdUYYz2jQ,iv:ijt1NySwGkmOcqoayhJ+jEn8uvtNja4FreI/pcChGuU=,tag:9fuAFBfeqcprAZqaZrwH0g==,type:str]
cachix-auth-token-value: ENC[AES256_GCM,data:OrcmrZUKupt72Aiv+/JubTl87u/E9oh44vA2Vh+cczR6jmqy+AV42efJQtLtRS7FAze7TD/f+OyDJiElpoBEDiSLeeIvrXoBRRy5aDnsdw7Yo696KwBHFRvKiEZq1n+Uk4AV3um90wyiqQW8tPzSvJcLTy4s6zHp3URo6DSc567jZ5ZvK8ACG8zGgX9CxliBybkCh1s=,iv:0Cf1Otpq7eVigU+FxRFdTNqZFTFA/IbBq53zfqdVuWs=,tag:utOsBfL9NFZ1359RLDFADQ==,type:str]
cachix-auth-token:
    env_key: ENC[AES256_GCM,data:oRU+5Z/7tgJnyorPmWPZqoc=,iv:ffm7SJLIbRxKk+lD1QMMdGoBvibZwIIhd7PPbZcp8to=,tag:zKIodQ8Nw50+tTgg9M+LoA==,type:str]
    value: ENC[AES256_GCM,data:7MhQxO7RvmPCkZLPE+yi69f6RDI6B8Jd2jJEDxcDPWWIxDwCH1+Sy0bZcsdO9uW4I2bXj9NKxnv2aiIIYE5wHg7kqg2jbokoAu2rqWAUcVN7CFOKA+pukZT298EsIVeQxUPXMSiKefVgr92hop/cuqO76zMtiApI5Y+fCt7WW67rF3oOcACWXBdTp/xByr85iBJd7M4=,iv:QP8U9Edc0Rv2QeYpORGxElXcrgRQ9GSuSQzQdVeJN8o=,tag:p05Q3ws2a9mbmXvZr7APgQ==,type:str]
    description: ENC[AES256_GCM,data:SBxAjaX8ARYiOIiU6ZiAEw0dEq1Shw==,iv:blzrBuuTmQtQRYeHxLKjmibzvw95rUmI4IAY5oRJJNc=,tag:RJUBly35ooR+ilPrVbH7Nw==,type:str]
    permission:
        read: ENC[AES256_GCM,data:qddNaQ==,iv:JhI66D6ZeAhfRcWjuDdqbt5e6XlMmyQt/+2/hkzydgE=,tag:viQUuGGPL4Pjp7P2zxFcxQ==,type:bool]
        write: ENC[AES256_GCM,data:XbmfVg==,iv:N5Lo4cRrbtWJIy789PRQV2jt9UfLl2OZDKBn8Wv3jl4=,tag:YcH04Bqx4iPDrXQsAAYfbA==,type:bool]
    created: ENC[AES256_GCM,data:KmIHFhk9LK/yfirSnP/i+XjV8hbKbAmJ,iv:Jr1AT/lW5dvaRRSxnINcOl8jJq1EoJrBOZqpPr1mlpg=,tag:Ozrx4Is0fhVc10fxKtMS+g==,type:str]
    expires: ENC[AES256_GCM,data:nd8rYM9NO3GbNd6OzYDSNCFBSky+bW+1,iv:xy9HNcT07B5juQu+9q7mbBgajDvRyteB7HlTFxBE2Qo=,tag:b96L+XMrEk6JjbkKx1Yzlw==,type:str]
    action: ENC[AES256_GCM,data:vwMzA7B79MYrra9iI28ADi+hO7ql,iv:oGv+nLqHaJBxoWWfU4rrf7ZGh9nK/8Z/zTASS9f4T4o=,tag:aV7hq5yGnJMoChyieMN0zQ==,type:str]
smb-secrets: ENC[AES256_GCM,data:M7xe8CzbIihjULi9NpCqPo+ZerS+6SxCHrPn1VGOcMPxLW5TfR8w+4rGI5r0LEinaKxu1waoGlvu,iv:b3eMuRvYgLGkjRf5PjEkXXDxSIwWHGLldW69t8tL9HQ=,tag:B1OIw0+Y292wyCavB+AxUA==,type:str]
wireless_secrets: ENC[AES256_GCM,data:eLR1yLhJRo/l1ZOL7lQgAKfvNDSKoOmaD7bgwlZ4X8bALp2zOdXIp0SmRDsY6FK/K6iHVYRlNyGwbLdbW6fL21cO3SHbXEkqsxylP7nZLMw=,iv:W3jMiL4hd55Emf+0I1lsAHb6nxZKDaeptnSCZyUT9XA=,tag:0DBDptG/WsniRxNf1jtGIA==,type:str]
wpa_supplicant_conf: ENC[AES256_GCM,data:JXP1n30BLFNF6IskfiptMMccoNyFgOQj+fM7jJfmrI+fGnzQJRGUB9rgezN2QVdtUMcQOltKjK5VO+Kv5dSGmQrjGv4tiHv9WEZjoNK9IfWRVk2RAwwMZYcSXGDqPBFxk8KqshxlohMfuzkMRfqLFbAUeL+4RkCaQXrdMBhLC8VR3HjAEhqizWcGhcTLXI4VHoBFu3UHNjetpvCFd4PeUXBQsqlEOgLSOoKL+VjkuLBlcIea002syw1UqVN6576jnb+i5givFc/MYCLFrVD7SzR+LxOL1d0YtigyM+362BNzKgjUyrOtaGZ4Wm8PkAqyoaQD2ItrUYMP1KF9o3f+azP9RnULCN0cGvZQWf8ppmYcvy1aVH2mcztCyo0DBDxFHhng0sUe8DDojZ84pacg4Lt319eOLOWfj5/JZXlZI1TFvU9npLMF2kYwQHPTLZu41PBTTuv0WP9tW9B+gxvDBRehIYrIPpQ08jVFtb2MXZD6N7Cy+C4T5SCOPfLRIm6eSHrqGfR+t4zC7M1erSiyadV9v6wxel8Euv7x+JLPKyxmn7E=,iv:QSz/HPRrtwmwI9SNqAVudnTWLSuQMVFKE/iro1P/b8c=,tag:MoBWnMx7RPSn6Mi39AWeYw==,type:str]
redshift:
    latitude: ENC[AES256_GCM,data:9XgxjV/QFzM=,iv:aS0HcCJ2hLXh9nLkKe1ZcJeYwZ0UxmqZ4ftTZ2lnQNo=,tag:z+skAQ9Mpshp7Fr6nu7N1g==,type:float]
    longitude: ENC[AES256_GCM,data:cU9UP2/Yeg==,iv:yR58yiWyeyCrrouV7OruclDEFQvGTcfC34TOyMlh948=,tag:Q9WSXepjUWcSg1JU8y+bGw==,type:float]
k3s-token: ENC[AES256_GCM,data:/drGQq8TvgAXT7FeWhQacIMAhDfVUaJHAraWCmACG7fqZKRngbuqy6Xn/CYd7mNPm4pan1byCN4hDqlvLhgReRGkptDaMdoQopW0RQP3m8JQTBY2V8rA/Q==,iv:gm9fb3Z/imKQ0q42SgmRD/Q+1Ufa4wra62Rg8lvD5cw=,tag:roBLsCXKZlIQCGz24WSd+A==,type:str]
users:
    geoffrey:
        password: ENC[AES256_GCM,data:gwkr7yycImwVDZeTeKq2CfXGE8P6sgfGv1Tnlow7Y41mv2heERR59ouBsIwNVaTUg+zfERRMniP0aSLfmk2RuQH8z1B0uPebXQ2y/wlmHedBWW+BTu93F+gVYgOru/d0OyejIeJfpUdL7w==,iv:IxXrIMxlglNpAdmmt0Z00zNqTt7xrg/hv2uRxhkU87U=,tag:qdo9KAqpROiBCsIXMI2Tpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yjgntgyscg5vw3pqpupqjcr92064a3k0d42fy6sk6lmujgv3e5fsdear9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aFRmTEJGYzdMb1cyN1JP
            WkQ1TnlLWWg4OUlDVGJuRHRhRWJPWGVhQUZRCjMrVEhrZFVpRXRidzc3VUU2aTl3
            QzFkYUdMckFoMm1CSkNiSFlkZkRXMTAKLS0tIDZpRXhvODBqYWJJTnAwOVRYVWVW
            RGt5dVczVlM3NXNmNE55cytYcU5XUVUKbLqpWG+hXkNRNwheW/SzDppBJt1fIcOB
            pS1H/APZ0rzxTVWzOprA882ikuDcpGlQ/Nkx1YrFdF37Qz3VSPhefg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kdp9ndxywv48mapkkejujvzfqhxzyzp6s7kp42u7ynu6q5e8sqkqp0w7sv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YXVrRW8wNmNJRkR6U0tN
            NTJJeTNDVEtPSGNUSFFpYTRtNGVySU5OVzFjCnpCSFhaVWRrbnVKVmZ5NS9nSUhO
            U250UEI2TUtNZkJsUFBnLzliSEh1aFUKLS0tIERGZGhnY0xvcGlaa3ZudVNRYTRM
            ZU1SZ0xVV1ptNWs2UXFIRjhNWitGNGcK9QfFLPeupNrtXhiNEO7fzswiDjhC4ElU
            vMzC93LOgYVuYkiClJutuOiDtg/yDZFhWeQ0MmWCWcdOWoky1eJ1mg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tpj92c7aqe8df7g3qf58vzcyevx53vhap3qkrxa9calpdtp5vvmqrd0de7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ1ZMUEJ0WUs2cHovazJG
            V0x2OHljQXFGR2cxcGFvUHVQTXM2VityNVUwCi9xRm5HeC9vcE5uTGZrVE1Sclhp
            ZVVHZlk5SlRzcCsyZTNEVXVnakdiWUkKLS0tIGpjSGxvY2RDN2lkSXJXaVNCOXJ5
            WlZrV3RXeVg2bDNKM3U0dWFqODJSamMKKhQO4Ah29dy2eXe4cln979mJ5lWp6WR7
            fXdrsugPoCkhnrfPNS2LqDjx77aYHu02cZjx4JWM22cSu2MOxbc6ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13sx384sda6z7lvg6arys4asl4j88t652y0r9km86n3xrsuh5hpzqndl9lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdGJjT0tlK0RVUDYzcW9x
            UXVTK09DZUlhelJNciswOE5uaGI1d3hUYWxVClZmUUoyaW11T2VjTmlFNEtKVWhu
            NGhYR0RyMkdsNk1Rci8yNTd0SjRpME0KLS0tIElGZFUyaC85QXhRWU5pMlJ2Smhi
            VHpjZGNIOXgrYk45YWpESEc0RnYyZjAKdTI2HBOM+pEMOf7kj+zFMmuWUbQ2mP3J
            nNdPMkHDlpmlwiEYLczoAKjtkSIHkdeiS3/1rXGl0e2f5UJg5EsTJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ahyztttw0jky84tzg5vzvhwvhy3c4ptw7zg4kv5jrn4ergjq2c3q4f76dv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y2VjU0FBYWFranZSSDhh
            NGcvaEJmY01TaVRtWWF2RkwySVNhNnA0U1U0CitYdVE0MUphSmI5NSt2SFl5a3k1
            UVY3TkhUdnBQZG41UmpwdzdWZ0ViSGMKLS0tIDB2eEh5MVRUUHkzVlgwODh5UmlK
            UUNKZnJvSnJUWWR2eHp4MXpxS25UNWcKIEwrP7LCByWqbNt4zjvCqJTK+P18nUpD
            sV2+nrgUx7raZc5b0zEEUlVTTN+M3pmxHZSUDvTf8iSUwcC+v6g2qQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z09vrs2ketcn244l43fjxgzuu22yp0q0tpkmh3s2grlqn8jgypeqgnnf9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NDJBaXRtYzNpV1VxcmZm
            cm05S0lKbDJ1YTVySG4rNzlHQmZ2NnRqMHhFCnZyNkZTMXJZTmhaSnFmcVRSU0Rv
            cExWMnV5MFBWY2Y1Uzg3Zzc2VmJPb3cKLS0tIDR4YzAxNWFmWWFUSHAzMjY3bmFW
            R1RHQkU1aGNHMzNIN3laeW8wME1lODgKNEN7u2FUDH8Zy4buuAxf6SH5f8fGHDb0
            0z84YX18fNWlzFCMXKbGroiRryOUemOPwaI/Vii0NdopRrFPectrvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jgsuq5wf3jv426rhst5saxc3etz29te3dx3tugg7466tje3layqvtar5f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Tjg1QW5ZTkQvTVp0My93
            TEF4cjJHYWZOck5vQ21RbE02Zm1xOHBKWjBFCnhzbUlvWll6Ulczc1N3aCt2RzI4
            RWVxSzNiZ3haZEhhN3FmRlNxUkw1ZWcKLS0tIGZNNGw2REd2SG1Fcy9FNWZmVjYz
            QSsrWDJ5aGVFSVRLbCs0VC9iTjFRZEUKMsdx0dTFR9X4VB9N8yJbA+NQz8QeszGZ
            qMzYFetha/6HZprpU7ij03t9KQNIsG+78JMnEGKwzpVLywqcPlAN8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mz6264gtrt32xj0hkzg620utf2eagx9p2k6yq63pxn4xnsv8jp8qn429m5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VXh4V1JZSjJUVE9CNjZj
            bThieFlXTitYUlVCT1dlWEp1blVENnR4YVJjCnpWeG1hMVl6S1JFczRWcmVBaXFk
            Vm5UcWdVS2tON0hLdlVXUVdLc1hiWlUKLS0tIElGM0FEVTVIekJkV0kxblZYN25N
            NTdGUm91bHBPTmpDdjRHcjlIemFmd1UKUfz7jmrNt6mT07v19BWOn6ocm7M9XcaZ
            BSVm2BWT4B+zTaZMs/Xclp3nxeWoHV7cMadjNPcV/7nB+PuhuHLOdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-28T19:26:59Z"
    mac: ENC[AES256_GCM,data:uHyiNl2488VvCcWyMcCIqnaFAl5VdO0jLAsUqLUI1Y6FJcP4x4Ysuk4MQKgFyCKMhTla4N6cpy+thwYJrKhBtDv/oNY7ssYdKq9nCr34a3XC1VRO+vRaELgPjcq/aeBX77IAoGNx9rFM8TcuLcvg2ukRKM4qyeI7y8u/+dFLPY4=,iv:2mEwTz4Xc3ciwr/UrG+qiCD2HHEx+CLJPXvHTBhleDk=,tag:6P6BItZRoBtADpHWVbZIWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
